-- liquibase formatted sql
-- changeset kaizen:192_seed_tags_edicao_ifo

INSERT INTO tags_acoes (id, name) VALUES
    ('PCA_MODIFICAR_IFO_AGUARDANDO_PROAD', 'Modificar IFO (Abertura)'),
    ('PCA_DELETAR_IFO_AGUARDANDO_PROAD', 'Deletar IFO (Abertura)'),
    ('PCA_VINCULAR_CONTRATOS_AGUARDANDO_PROAD', 'Vincular Contratos (Abertura)'),

    ('PCA_MODIFICAR_IFO_ABERTO', 'Modificar IFO (Aberto)'),
    ('PCA_DELETAR_IFO_ABERTO', 'Deletar IFO (Aberto)'),
    ('PCA_VINCULAR_CONTRATOS_ABERTO', 'Vincular Contratos (Aberto)'),

    ('PCA_MODIFICAR_IFO_EM_CONSULTA', 'Modificar IFO (Em Consulta)'),
    ('PCA_DELETAR_IFO_EM_CONSULTA', 'Deletar IFO (Em Consulta)'),
    ('PCA_VINCULAR_CONTRATOS_EM_CONSULTA', 'Vincular Contratos (Em Consulta)'),

    ('PCA_MODIFICAR_IFO_RETORNO_AREAS', 'Modificar IFO (Retorno Áreas)'),
    ('PCA_DELETAR_IFO_RETORNO_AREAS', 'Deletar IFO (Retorno Áreas)'),
    ('PCA_VINCULAR_CONTRATOS_RETORNO_AREAS', 'Vincular Contratos (Retorno Áreas)'),

    ('PCA_MODIFICAR_IFO_CONSOLIDACAO_CCA', 'Modificar IFO (Consolidação CCA)'),
    ('PCA_DELETAR_IFO_CONSOLIDACAO_CCA', 'Deletar IFO (Consolidação CCA)'),
    ('PCA_VINCULAR_CONTRATOS_CONSOLIDACAO_CCA', 'Vincular Contratos (Consolidação CCA)'),

    ('PCA_MODIFICAR_IFO_VALIDACAO_GEJUT', 'Modificar IFO (Validação GEJUT)'),
    ('PCA_DELETAR_IFO_VALIDACAO_GEJUT', 'Deletar IFO (Validação GEJUT)'),
    ('PCA_VINCULAR_CONTRATOS_VALIDACAO_GEJUT', 'Vincular Contratos (Validação GEJUT)'),

    ('PCA_MODIFICAR_IFO_APRECIACAO_SGJT', 'Modificar IFO (Apreciação SGJT)'),
    ('PCA_DELETAR_IFO_APRECIACAO_SGJT', 'Deletar IFO (Apreciação SGJT)'),
    ('PCA_VINCULAR_CONTRATOS_APRECIACAO_SGJT', 'Vincular Contratos (Apreciação SGJT)'),

    ('PCA_MODIFICAR_IFO_EM_COMITES', 'Modificar IFO (Comitês)'),
    ('PCA_DELETAR_IFO_EM_COMITES', 'Deletar IFO (Comitês)'),
    ('PCA_VINCULAR_CONTRATOS_EM_COMITES', 'Vincular Contratos (Comitês)'),

    ('PCA_MODIFICAR_IFO_REMESSA_DG', 'Modificar IFO (Remessa DG)'),
    ('PCA_DELETAR_IFO_REMESSA_DG', 'Deletar IFO (Remessa DG)'),
    ('PCA_VINCULAR_CONTRATOS_REMESSA_DG', 'Vincular Contratos (Remessa DG)')
ON CONFLICT (id) DO NOTHING;

-- rollback DELETE FROM tags_acoes WHERE id IN (
-- rollback   'PCA_MODIFICAR_IFO_AGUARDANDO_PROAD', 'PCA_DELETAR_IFO_AGUARDANDO_PROAD', 'PCA_VINCULAR_CONTRATOS_AGUARDANDO_PROAD',
-- rollback   'PCA_MODIFICAR_IFO_ABERTO', 'PCA_DELETAR_IFO_ABERTO', 'PCA_VINCULAR_CONTRATOS_ABERTO',
-- rollback   'PCA_MODIFICAR_IFO_EM_CONSULTA', 'PCA_DELETAR_IFO_EM_CONSULTA', 'PCA_VINCULAR_CONTRATOS_EM_CONSULTA',
-- rollback   'PCA_MODIFICAR_IFO_RETORNO_AREAS', 'PCA_DELETAR_IFO_RETORNO_AREAS', 'PCA_VINCULAR_CONTRATOS_RETORNO_AREAS',
-- rollback   'PCA_MODIFICAR_IFO_CONSOLIDACAO_CCA', 'PCA_DELETAR_IFO_CONSOLIDACAO_CCA', 'PCA_VINCULAR_CONTRATOS_CONSOLIDACAO_CCA',
-- rollback   'PCA_MODIFICAR_IFO_VALIDACAO_GEJUT', 'PCA_DELETAR_IFO_VALIDACAO_GEJUT', 'PCA_VINCULAR_CONTRATOS_VALIDACAO_GEJUT',
-- rollback   'PCA_MODIFICAR_IFO_APRECIACAO_SGJT', 'PCA_DELETAR_IFO_APRECIACAO_SGJT', 'PCA_VINCULAR_CONTRATOS_APRECIACAO_SGJT',
-- rollback   'PCA_MODIFICAR_IFO_EM_COMITES', 'PCA_DELETAR_IFO_EM_COMITES', 'PCA_VINCULAR_CONTRATOS_EM_COMITES',
-- rollback   'PCA_MODIFICAR_IFO_REMESSA_DG', 'PCA_DELETAR_IFO_REMESSA_DG', 'PCA_VINCULAR_CONTRATOS_REMESSA_DG'
-- rollback );
