-- liquibase formatted sql

-- changeset kaizen:225_seed_sgsi_indicador splitStatements:false
-- Seed REAL: 31 indicadores (5 com meta/tolerância pactuadas; 26 aguardando deliberação do
-- CGSI — meta NULL, decisão D-08). Sem medições (vazias na origem). Origem: SGSI/04_indicador.sql.

INSERT INTO sgsi_indicador (seed_key,instrumento_codigo,tarefa_id,nome,referencia,responsavel,unidade,meta,tolerancia,direcao) VALUES
('POSIC:9001','POSIC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='POSIC' AND numero=9001),'% de Instrumentos Normativos Complementares adequados e republicados conforme a POSIC','POSIC art. 7º','NSI','%',100,80,'>='),
('POSIC:9005','POSIC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='POSIC' AND numero=9005),'Testes de invasão (pentests) realizados nos últimos 12 meses','POSIC art. 8º, II','NSI','testes',1,1,'>='),
('POSIC:9007','POSIC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='POSIC' AND numero=9007),'Tempo médio de comunicação de desligamentos DGP → revogação de acessos','POSIC art. 11 §2º','DGP + DITI','horas',1,2,'<='),
('POSIC:9002','POSIC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='POSIC' AND numero=9002),'% de riscos cibernéticos com dono de risco formalmente designado','POSIC art. 9º §1º','NSI','%',100,90,'>='),
('POSIC:9006','POSIC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='POSIC' AND numero=9006),'Relatórios de maturidade ENSEC-PJ reportados no ano','POSIC art. 8º, III','NSI','relatórios',1,1,'>='),
('IAM:44','IAM',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='IAM' AND numero=44),'Operar o painel de indicadores (KPIs) com reporte trimestral ao CGSI e anual à Presidência','Metas mensuráveis do PDZT (art. 42)','DSIDC','%',NULL,NULL,'>='),
('PUA:33','PUA',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PUA' AND numero=33),'Operar o painel de indicadores (KPIs) de conformidade da PUA, com reporte trimestral ao CGSI','Fiscalização e reporte (POSIC art. 8º)','NSI','%',NULL,NULL,'>='),
('PCI:36','PCI',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PCI' AND numero=36),'Operar o painel de indicadores de conformidade da PCI, com reporte semestral ao CGSI','Indicadores mínimos: repositórios classificados, sistemas com rotulagem, exceções vigentes, incidentes Restrita+ (art. 46)','NSI → CGSI','%',NULL,NULL,'>='),
('PCUC:16','PCUC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PCUC' AND numero=16),'Editar a ITO do cronograma do Plano de Transição Pós-Quântica (marcos, indicadores e esquemas híbridos admitidos)','Prazo de 90 dias (arts. 49, IV, e 57, IV)','NSI + DITI','%',NULL,NULL,'>='),
('PCUC:42','PCUC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PCUC' AND numero=42),'Operar o painel de indicadores de conformidade criptográfica com reporte semestral ao CGSI','Monitoramento contínuo e reporte (arts. 9º, VI, e 54, IV)','NSI','%',NULL,NULL,'>='),
('PGA:19','PGA',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PGA' AND numero=19),'Elaborar e aprovar no CGSI o plano de implantação do inventário automatizado, com metas escalonadas de cobertura e cronograma de reconciliação inicial','Obrigação em 120 dias (art. 54)','SGJT + DITI + NSI','%',NULL,NULL,'>='),
('PGA:47','PGA',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PGA' AND numero=47),'Operar o painel de indicadores da gestão de ativos e reportar semestralmente ao CGSI (cobertura, ativos não autorizados, EOL, descartes certificados, reconcilia','Indicadores obrigatórios e iGovTIC-JUD (art. 47; Res. CNJ 370/2021)','NSI + DITI','%',NULL,NULL,'>='),
('PGA:50','PGA',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PGA' AND numero=50),'Monitorar a aderência dos novos contratos de TIC às cláusulas de segurança, sanitização e retenção de mídia','Cadeia de suprimentos conforme (art. 24; Res. CNJ 468/2022)','COMPRAS + NSI','%',NULL,NULL,'>='),
('PPINC:23','PPINC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PPINC' AND numero=23),'Estabelecer o fluxo de triagem e acionamento da ETIR (SLA de 2 horas para eventos altos/críticos) a partir dos alertas do monitoramento','Acionamento tempestivo e contenção preventiva (arts. 9º, 37)','NSI + ETIR','%',NULL,NULL,'>='),
('PPINC:32','PPINC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PPINC' AND numero=32),'Apurar e reportar os indicadores de desempenho (KPIs) do PPINC ao CGSI e à Presidência, com relatório anual ao CNJ','Medição de efetividade e maturidade (arts. 47, 48; POSIC art. 8º, III; ENSEC-PJ)','NSI + CGSI','%',NULL,NULL,'>='),
('PGCRC:25','PGCRC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PGCRC' AND numero=25),'Estabelecer o compartilhamento de indicadores de comprometimento (IoC) com o CPTRIC-PJ e a Rede Nacional de Cibersegurança','Cooperação e defesa coletiva (art. 44; art. 22)','NSI + ETIR','%',NULL,NULL,'>='),
('PIILC:31','PIILC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PIILC' AND numero=31),'Operar o painel de indicadores do Protocolo e reportar semestralmente ao CGSI','Monitoramento por indicadores (art. 47)','NSI / CGSI','%',NULL,NULL,'>='),
('PIILC:34','PIILC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PIILC' AND numero=34),'Monitorar a aderência dos novos contratos de TIC/nuvem às cláusulas de preservação e requisição de evidências','Cadeia de suprimentos apta à preservação (art. 23; Res. CNJ 468/2022)','COMPRAS + NSI + AJ','%',NULL,NULL,'>='),
('PPIC:4','PPIC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PPIC' AND numero=4),'Editar ITO Conjunta DITI/NSI — parâmetros de RTO/RPO por nível de criticidade e metodologia da BIA','Prazo de 90 dias (art. 40, I; art. 11, p.ú.)','DITI + NSI','%',NULL,NULL,'>='),
('PPIC:13','PPIC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PPIC' AND numero=13),'Fixar e aprovar os RTO/RPO de cada serviço essencial, vinculando redundância, backup e recuperação','Metas de continuidade (art. 20)','NSI + Gestores','%',NULL,NULL,'>='),
('PPIC:39','PPIC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PPIC' AND numero=39),'Definir e operar o painel de indicadores do art. 36 com reporte semestral ao CGSI e à Presidência','Art. 36; metas ENSEC-PJ','NSI','%',NULL,NULL,'>='),
('PBRD:8','PBRD',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PBRD' AND numero=8),'Elaborar ITO de metas operacionais de RPO/RTO por sistema (dentro dos tetos do art. 11)','Art. 35, I c/c art. 11, § 1º — PRAZO LEGAL: 120 dias (M+4); homologação CGSI (art. 7º, II)','DITI + NSI; CGSI homologa','%',NULL,NULL,'>='),
('PBRD:37','PBRD',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PBRD' AND numero=37),'Publicar os indicadores da PBRD no painel de gestão do SGSI/TJGO','Art. 37 — taxa de sucesso, cobertura 3-2-1-1-0, testes, aderência a RPO/RTO','NSI + DITI','%',NULL,NULL,'>='),
('PECC:3','PECC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PECC' AND numero=3),'Deliberar no CGSI as diretrizes estratégicas e prioridades da educação (públicos-alvo prioritários, metas iniciais dos indicadores, apetite de risco das simulaç','Governança colegiada e aprovação de metas (arts. 11 e 36, § único; POSIC art. 3º, § 1º)','CGSI + SGJT','%',NULL,NULL,'>='),
('PECC:11','PECC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PECC' AND numero=11),'Elaborar e aprovar o 1º Plano Bianual de Educação e Cultura em Cibersegurança (públicos, trilhas, cargas horárias, cronograma, metas, recursos)','Instrumento de planejamento obrigatório (arts. 15 e 43)','NSI + EJUG','%',NULL,NULL,'>='),
('PECC:17','PECC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PECC' AND numero=17),'Construir o painel de indicadores da PECC (conclusão, cliques, reporte, tempo de reporte, certificações, participação) com dados agregados e pseudonimizados','Mensurabilidade e reporte (arts. 36; 37)','DITI + NSI','%',NULL,NULL,'>='),
('PECC:31','PECC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PECC' AND numero=31),'Consolidar e submeter ao CGSI e à Presidência o 1º Relatório Anual de Resultados da PECC (evolução dos indicadores, lições aprendidas, ajustes)','Reporte anual e alimentação da maturidade da POSIC (arts. 37; POSIC art. 8º, III)','NSI + SGJT','%',NULL,NULL,'>='),
('PECC:32','PECC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PECC' AND numero=32),'Revisar o Plano Bianual e preparar o ciclo seguinte, com metas ajustadas e novas prioridades temáticas','Revisão ordinária e melhoria contínua (arts. 15; 47)','NSI + EJUG + CGSI','%',NULL,NULL,'>='),
('PECC:34','PECC',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PECC' AND numero=34),'Monitorar continuamente os indicadores da PECC e reportar tendências ao CGSI, ajustando ações conforme a série histórica','Mensuração e melhoria contínua (arts. 4º, V e VI; 36; 37)','NSI + CGSI','%',NULL,NULL,'>='),
('PSFT:33','PSFT',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PSFT' AND numero=33),'Consolidar e reportar ao CGSI e à Presidência os indicadores de postura de segurança da cadeia de suprimentos','Indicadores da cadeia e maturidade (art. 52; ENSEC-PJ)','NSI + CGSI','%',NULL,NULL,'>='),
('PDSS:39','PDSS',(SELECT id FROM sgsi_tarefa WHERE instrumento_codigo='PDSS' AND numero=39),'Consolidar indicadores institucionais de segurança de software e reportar periodicamente ao CGSI','Indicadores e reporte (art. 30; art. 10, VI)','NSI + DSTI','%',NULL,NULL,'>=')
ON CONFLICT (seed_key) DO NOTHING;
