--liquibase formatted sql

--changeset system:251_remover_permissoes_deletar_ifo
DELETE FROM tags_acoes WHERE id IN (
    'PCA_FOR_DELETAR_IFO_ABERTO',
    'PCA_FOR_DELETAR_IFO_AGUARDANDO_PROAD',
    'PCA_FOR_DELETAR_IFO_APRECIACAO_SGJT',
    'PCA_FOR_DELETAR_IFO_CONSOLIDACAO_CCA',
    'PCA_FOR_DELETAR_IFO_EM_COMITES',
    'PCA_FOR_DELETAR_IFO_EM_CONSULTA_1',
    'PCA_FOR_DELETAR_IFO_EM_CONSULTA_2',
    'PCA_FOR_DELETAR_IFO_REMESSA_DG',
    'PCA_FOR_DELETAR_IFO_RETORNO_AREAS',
    'PCA_FOR_DELETAR_IFO_VALIDACAO_GEJUT'
);
