--liquibase formatted sql

--changeset kaizen:180_create_pac_capacitacao
-- Migration 180: Matriz do Plano Anual de Capacitação (PAC).
--
-- Sustenta o módulo "Plano Anual de Capacitação" (Pessoas). A coluna `modulo` separa as
-- submatrizes ('ti' = Tecnologia da Informação, 'apoio' = Apoio Judiciário), permitindo a
-- mesma tabela atender os dois submenus.
--
-- Colunas exibidas na TABELA: codigo, area_demandante, evento_capacitacao, prioridade,
-- numero_vagas, modalidade, estimativa_custo. As demais (categoria, tema,
-- objetivo_justificativa, publico_alvo, competencias, observacoes) compõem o painel de
-- detalhes exibido ao expandir a linha.
--
-- SEGURANÇA (Zero Downtime): tabela nova, aditiva.

CREATE TABLE IF NOT EXISTS pac_capacitacao (
    id                    BIGSERIAL PRIMARY KEY,
    modulo                VARCHAR(20)  NOT NULL DEFAULT 'ti',
    codigo                VARCHAR(20),
    area_demandante       TEXT,
    categoria             VARCHAR(40),
    tema                  TEXT,
    evento_capacitacao    TEXT,
    objetivo_justificativa TEXT,
    publico_alvo          VARCHAR(160),
    prioridade            VARCHAR(20),
    numero_vagas          INTEGER,
    competencias          VARCHAR(80),
    modalidade            VARCHAR(40),
    estimativa_custo      TEXT,
    observacoes           TEXT,
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted            BOOLEAN   DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_pac_capacitacao_modulo ON pac_capacitacao (modulo, is_deleted);

INSERT INTO pac_capacitacao
    (modulo, codigo, area_demandante, categoria, tema, evento_capacitacao, objetivo_justificativa,
     publico_alvo, prioridade, numero_vagas, competencias, modalidade, estimativa_custo, observacoes)
VALUES
('ti','PC01','Coordenadoria de Suporte em Tecnologia da Informação','Curso','Gestão de Serviços','Ninja GLPI – Iniciante','Treinamento prático para utilização do sistema GLPI, possibilitando melhor controle de chamados, organização de ativos de TI, acompanhamento de demandas e melhoria na rastreabilidade das atividades da área.','Servidores da CSTI','Alta',NULL,'Competência Técnica','EAD',NULL,'Curso na plataforma Udemy'),
('ti','PC02','Coordenadoria de Suporte em Tecnologia da Informação','Curso','Gestão Ágil de Projetos','Gestão Ágil de Projetos com Scrum, Kanban e Ágil Escalado','Capacidade de planejar, conduzir e melhorar a entrega de produtos/serviços por meio de métodos ágeis.','Servidores da CSTI','Alta',NULL,'Competência Gerencial','EAD',NULL,'Curso na plataforma Udemy'),
('ti','PC03','Coordenadoria de Suporte em Tecnologia da Informação','Curso','Planejamento e Gestão de Projetos','Planejamento e Gestão de Projetos','Capacidade de planejar, executar, monitorar e encerrar projetos de forma estruturada, definindo escopo, prazos, custos, recursos, riscos e comunicação para entregar os resultados acordados com qualidade e governança.','Servidores da CSTI','Alta',NULL,'Competência Gerencial','EAD',NULL,'Curso na plataforma Udemy'),
('ti','PC04','Diretoria de Soluções em Tecnologia da Informação','Evento','Tecnologia e Inovação no Judiciário','EXPOJUD 2026','Permitir a troca de experiências, aprendizado sobre inovação no setor público e networking com especialistas em governança digital e transformação digital no Judiciário.','Servidores da DSTI','Alta',2,'Competência Estratégica','Presencial','R$0.00',NULL),
('ti','PC05','Diretoria de Soluções em Tecnologia da Informação','Evento','Desenvolvimento de Software','TheDevConf 2026 The Developer''s Conference','Permitir a troca de experiências com o setor privado, atualização sobre novas ferramentas, produtos, tecnicas e boas práticas na área de TI.','Servidores da DSTI','Alta',5,'Competência Técnica','Presencial','R$1,750.00',NULL),
('ti','PC06','Diretoria de Soluções em Tecnologia da Informação','Evento','Inovação e Agilidade no Setor Público','Agile Trends GOV 2026','Permitir a troca de experiências, aprendizado sobre inovação no setor público e networking com especialistas em governança digital e transformação digital no Judiciário.','Servidores da DSTI','Alta',4,'Competência Estratégica','Presencial','R$2,885.00',NULL),
('ti','PC07','Diretoria de Soluções em Tecnologia da Informação','Evento','Experiência do Usuário (UX)','UX (User Experience ou Experiência do Usuário)','Permitir a troca de experiências, aprendizado sobre inovação e networking com especialistas em experiência de usuário.','Servidores da DSTI','Alta',3,'Competência Técnica','Presencial','R$899.00',NULL),
('ti','PC08','Coordenadoria de Governança e Planejamento de TIC','Curso','Inteligência Artificial','Inteligência Artificial e Ferramentas Generativas','Capacitar servidores públicos estaduais na compreensão dos conceitos fundamentais de Inteligência Artificial e Ferramentas Generativas, promovendo a aplicação dessas tecnologias em suas atividades rotineiras para otimizar processos, melhorar a eficiência operacional e fomentar a inovação no setor público.','Servidores da CGP','Média',NULL,'Competência Técnica','EAD','$0,00','Escola de Governo de Goiás'),
('ti','PC09','Coordenadoria de Governança e Planejamento de TIC','Curso','Governança Pública','Fundamentos em Governança Pública','Apresentar os aspectos introdutórios e as dimensões da Governança Pública, incluindo os princípios que devem ser seguidos para induzir boas práticas nos trabalhos da administração pública.','Servidores da CGP','Média',NULL,'Competência Estratégica','EAD','$0,00','Escola de Governo de Goiás'),
('ti','PC10','Coordenadoria de Governança e Planejamento de TIC','Curso','Governança Pública','Fundamentos da Liderança Pública','Desenvolver o autoconhecimento, reconhecimento de forças e propósito, com foco na inteligência emocional, empatia, auto responsabilidade e autodisciplina; desenvolver habilidades de comunicação consciente, gestão relacional e negociação com base em confiança e desenvolver o uso inteligente do tempo, análise de dados e visão de futuro, para a entrega efetiva de valor público.','Servidores da CGP','Média',NULL,'Competência Gerencial','EAD','$0,00','Escola de Governo de Goiás'),
('ti','PC11','Coordenadoria de Infraestrutura Tecnológica','Curso','Telecomunicações','Treinamentos oficiais Avaya: Avaya 71202V, Avaya 72202V, Avaya 72301V','Esse pacote de treinamentos oficiais Avaya contemplam a integração e o suporte ao sistema de telefonia VoIP do TJGO. É de suma importância que os analistas responsáveis pela ferramenta façam o treinamento','Servidores da CITEC','Média',2,'Competência Técnica','EAD','R$124.070,69','Plataforma Web Next Point'),
('ti','PC12','Coordenadoria de Suporte em Tecnologia da Informação','Curso','Governança','IT Governance Management: Governança de TI','Capacitação voltada ao entendimento de estruturas de governança, papéis e responsabilidades da TI, permitindo alinhar a área de tecnologia aos objetivos do negócio, melhorar a tomada de decisão e reduzir riscos operacionais e de conformidade.','Servidores da CSTI','Média',NULL,'Competência Estratégica','EAD',NULL,'Curso na plataforma Udemy'),
('ti','PC13','Coordenadoria de Suporte em Tecnologia da Informação','Curso','Gestão de Serviços','O ITIL e as Práticas de Gestão (2026)','Formação para aplicação das boas práticas do framework ITIL, com foco na padronização de processos, melhoria do atendimento ao usuário, controle de incidentes e aumento da eficiência operacional dos serviços de TI.','Servidores da CSTI','Média',NULL,'Competência Técnica','EAD',NULL,'Curso na plataforma Udemy'),
('ti','PC14','Coordenadoria de Suporte em Tecnologia da Informação','Curso','Gestão de Serviços','IT Service Management: Gestão de Serviços de TI (ITSM/GSTI)','Curso direcionado à gestão estruturada de serviços de TI, com foco em qualidade, indicadores de desempenho e melhoria contínua, contribuindo para maior disponibilidade dos sistemas e melhor experiência dos usuários internos.','Servidores da CSTI','Média',NULL,'Competência Técnica','EAD',NULL,'Curso na plataforma Udemy'),
('ti','PC15','Coordenadoria de Suporte em Tecnologia da Informação','Curso','Gestão do Tempo','Gestão do Tempo, Organização, Produtividade e GTD','Capacidade de organizar e priorizar demandas para executar o trabalho com foco e previsibilidade.','Servidores da CSTI','Média',NULL,'Competência Comportamental','EAD',NULL,'Curso na plataforma Udemy'),
('ti','PC16','Coordenadoria de Contratos e Aquisições de TIC','Curso','Inteligência Artificial','Engenharia de Prompts','Capacitar servidores para usar engenharia de prompts de forma estratégica para extrair o máximo dos principais chatbots de IA, atualmente utilizados nos processos de contratações de TI','Servidores da CCA','Média',NULL,'Competência Técnica','EAD',NULL,'Curso na plataforma Udemy'),
('ti','PC17','Coordenadoria de Contratos e Aquisições de TIC','Curso','Inteligência Artificial','Agentes de IA','Automatizar tarefas repetitivas para aumentar produtividade no dia a dia nas atividades da Coordenadoria e usar IA para automatizar e processar dados, tarefas automáticas e gerar insights para tomada de decisão.','Servidores da CCA','Média',NULL,'Competência Técnica','EAD',NULL,'Curso na plataforma Udemy'),
('ti','PC18','Coordenadoria de Governança e Planejamento de TIC','Evento','BigData, Data Science e Inteligência Artificial','Data Science Summit','O Data Science Summit, tradicionalmente, busca discutir técnicas, tecnologias e tendências em Ciência e Análise de Dados para suportar Smart Things e Smart People, trazendo conteúdo na forma de experiências, sucessos e insucessos aplicados a diversos setores','Servidores da CGP','Média',3,'Competência Técnica','EAD','Ainda não definido','Evento em Curitiba'),
('ti','PC19','Coordenadoria de Infraestrutura Tecnológica','Curso','Segurança da Informação','Segurança da Informação','Necessidade de fortalecer os conhecimentos sobre segurança da informação, mais especificamente nos casos de phishing no ambiente corporativo','Servidores da CITEC','Baixa',NULL,'Competência Técnica','EAD','$0,00','ENAJU'),
('ti','PC20','Coordenadoria de Infraestrutura Tecnológica','Curso','Programação','Programação Python','A linguagem é utilizada em diversas áreas da TI. Desde a criação de pequenos scripts de automação até modelos de LLM em inteligência artificial','Servidores da CITEC','Baixa',NULL,'Competência Técnica','EAD','$0,00','Curso na plataforma Udemy'),
('ti','PC21','Coordenadoria de Infraestrutura Tecnológica','Curso','Nuvem','AWS Cloud Certification Course','O TJGO utiliza diversos serviços da plataforma de nuvem AWS. É imperativo que os servidores sejam capacitados para obter o melhor desempenho da plataforma.','Servidores da CITEC','Baixa',NULL,'Competência Técnica','EAD','$0,00','Curso na plataforma Udemy'),
('ti','PC22','Coordenadoria de Infraestrutura Tecnológica','Curso','Segurança da Informação','ISC2 CISSP Full Course','A área de segurança computacional é extremamente dinâmica e demanda constante atualização. O objetivo deste curso é justamente preparar o profissional para a certificação ISC2 CISSP em segurança.','Servidores da CITEC','Baixa',NULL,'Competência Técnica','EAD','$0,00','Curso na plataforma Udemy'),
('ti','PC23','Coordenadoria de Infraestrutura Tecnológica','Curso','OpenShift','OpenShift for The Absolute Beginners','Utilizamos o OpenShift para hospedar diversas aplicações no TJGO. É de suma importância que tenhamos diversos analistas capacitados.','Servidores da CITEC','Baixa',NULL,'Competência Técnica','EAD','$0,00','Curso na plataforma Udemy'),
('ti','PC24','Coordenadoria de Infraestrutura Tecnológica','Curso','Contratação','Nova Lei de Licitações','O processo de contratação representa uma parte muito importante do processo de gestão e controle de T.I. no TJGO. É de suma importância que tenhamos profissionais versados na matéria contratações.','Servidores da CITEC','Baixa',NULL,'Competência Técnica','EAD','$0,00','Curso na plataforma Udemy'),
('ti','PC25','Coordenadoria de Infraestrutura Tecnológica','Curso','Monitoramento','Curso Zabbix 7','O Zabbix é a principal ferramenta de monitoramento que utilizamos no TJGO. Faz-se importante manter os analistas atualizados na utilização da ferramenta.','Servidores da CITEC','Baixa',NULL,'Competência Técnica','EAD','$0,00','Curso na plataforma Udemy'),
('ti','PC26','Coordenadoria de Infraestrutura Tecnológica','Curso','Gestão de Serviços','GLPI 10 Avançado','Atualmente o TJGO utiliza a ferramenta GLPI para controle de mudanças, abertura de chamados e implementação de diversos outros aspectos do ITIL no Tribunal. Conhecer bem a ferramenta é imprescindível para um bom uso e gerenciamento.','Servidores da CITEC','Baixa',NULL,'Competência Técnica','EAD','$0,00','Curso na plataforma Udemy'),
('ti','PC27','Coordenadoria de Infraestrutura Tecnológica','Curso','Windows Server 2022 + 2019','Windows Server 2022 + 2019','O TJGO utiliza o Windows Server para diversas finalidades em seu datacenter. Se manter atualizado no uso e gestão da ferramenta é de suma importância.','Servidores da CITEC','Baixa',NULL,'Competência Técnica','EAD','$0,00','Curso na plataforma Udemy'),
('ti','PC28','Coordenadoria de Infraestrutura Tecnológica','Curso','Inteligência Artificial','Soluções Preditivas Baseadas em Dados com o Uso de R e de Python','As ferramentas de machine learning são imprescindíveis nos dias atuais. Aprender a utilizar R e Python é basilar no processo de utilização de machine learning.','Servidores da CITEC','Baixa',NULL,'Competência Técnica','EAD','$0,00','ENAP'),
('ti','PC29','Coordenadoria de Infraestrutura Tecnológica','Curso','Infraestrutura','O papel do DevOps Na transformação digital dos serviços públicos','A metodologia DevOps é padrão nas T.I.s de todo o mundo. O TJGO também utiliza essa metodologia. É de suma importância que os analistas tenham conhecimento de todos os paradigmas dessa metodologia.','Servidores da CITEC','Baixa',NULL,'Competência Técnica','EAD','$0,00','ENAP'),
('ti','PC30','Coordenadoria de Infraestrutura Tecnológica','Curso','Gestão de Contratos','Gestão e Fiscalização de Contratos','A compreensão das atribuições legais dos gestores e fiscais de contratos é imprescindível para um correto controle e gestão dos contratos da administração.','Servidores da CITEC','Baixa',NULL,'Competência Gerencial','EAD','$0,00','Escola de Governo de Goiás'),
('ti','PC31','Coordenadoria de Infraestrutura Tecnológica','Curso','Cibersegurança','Analista de Cibersegurança Junior','É imprescindível que os analistas tenham conhecimentos sobre cibersegurança. Indiferente do campo de atuação dos mesmos.','Servidores da CITEC','Baixa',NULL,'Competência Técnica','EAD','$0,00','Cisco Networking Academy'),
('ti','PC32','Coordenadoria de Infraestrutura Tecnológica','Evento','Inteligência Artificial','Public Sector Summit - Edição América Latina','Evento que apresenta soluções diversas para IA, cibersegurança, nuvem entre outros tópicos','Servidores da CITEC','Baixa',NULL,'Competência Estratégica','EAD','$0,00','Evento em Brasília'),
('ti','PC33','Coordenadoria de Suporte em Tecnologia da Informação','Curso','Comunicação e Oratória','Comunicação e Oratória','Capacidade de comunicar ideias com clareza, segurança e persuasão.','Servidores da CSTI','Baixa',NULL,'Competência Comportamental','EAD',NULL,'Curso na plataforma Udemy'),
('ti','PC34','Coordenadoria de Suporte em Tecnologia da Informação','Curso','Desenvolvimento Pessoal e Profissional','Desenvolvimento Pessoal e Profissional','Curso voltado ao aprimoramento de competências comportamentais, organização, comunicação e gestão do tempo, contribuindo para aumento da produtividade, melhor relacionamento com usuários e equipes e maior eficiência na execução das atividades profissionais.','Servidores da CSTI','Baixa',NULL,'Competência Comportamental','EAD',NULL,'Curso na plataforma Udemy'),
('ti','PC35','Coordenadoria de Governança e Planejamento de TIC','Evento','Tecnologia e Inovação na Justiça','ExpoJud','Permitir a troca de experiências, aprendizado sobre inovação no setor público e networking com especialistas em governança digital, contratações públicas e transformação digital no Judiciário.','Servidores da CGP','Baixa',3,'Competência Estratégica','Presencial','$0,00','Evento em Brasília'),
('ti','PC36','Coordenadoria de Governança e Planejamento de TIC','Evento','Governança, Gestão, Transformação digital e Inovação','CONIP','Permitir a troca de experiências, aprendizado sobre inovação no setor público e networking com especialistas em governança digital, contratações públicas e transformação digital no Judiciário.','Servidores da CGP','Baixa',3,'Competência Estratégica','Presencial','$0,00','Evento em Brasília'),
('ti','PC37','Diretoria de Soluções em Tecnologia da Informação','Evento','Tecnologia e Inovação no Judiciário','CONIP JUDICIÁRIO 2026','Permitir a troca de experiências, aprendizado sobre inovação no setor público e networking com especialistas em governança digital e transformação digital no Judiciário.','Servidores da DSTI','Baixa',2,'Competência Estratégica','Presencial','R$0.00',NULL);

--rollback DROP TABLE pac_capacitacao;
