-- liquibase formatted sql

-- changeset kaizen:220_seed_sgsi_instrumento splitStatements:false
-- Seed REAL (14 instrumentos: PSI/TJGO basilar + 13 complementares). Idempotente (ON CONFLICT).
-- Origem: SGSI/01_instrumento.sql (colega). Só a tabela foi prefixada p/ sgsi_.

INSERT INTO sgsi_instrumento (codigo,ordem,numeral_romano,sigla_oficial,nome_curto,nome_completo,titulo_plano,cor_hex,restrito,ancora) VALUES
('POSIC',0,NULL,'PSI/TJGO','Política de Segurança da Informação e Comunicação','POSIC/TJGO — Norma basilar do SGSI (Decreto Judiciário) · institui o SGSI/TJGO','POSIC/TJGO — Política de Segurança da Informação e Comunicação · norma estratégica basilar do Sistema de Gestão de Segurança da Informação','#8a6d1f',false,'2026-07-01'),
('IAM',1,'I','IAM/TJGO','Gestão de Identidades e Acessos','Decreto de Gestão de Identidades, Credenciais e Acessos — Instrumento I','PLANO DE TRABALHO 5W2H + GANTT — Decreto de Gestão de Identidades, Credenciais e Acessos do TJGO','#2563eb',false,'2026-07-01'),
('PUA',2,'II','PUA/TJGO','Uso Aceitável de Ativos de TIC','Política de Uso Aceitável (PUA) V2 — Instrumento II + ITOs DITI/NSI 01-04/2026','PLANO DE TRABALHO 5W2H + GANTT — Política de Uso Aceitável (PUA) dos Ativos de TIC do TJGO','#0891b2',false,'2026-07-01'),
('PCI',3,'III','PCI/TJGO','Classificação da Informação','PCI/TJGO V2 — Instrumento Normativo Complementar III','PLANO DE TRABALHO 5W2H + GANTT — Política de Classificação da Informação (PCI/TJGO V2 — harmonizada com a Resolução nº 199/2022)','#7c3aed',false,'2026-07-01'),
('PCUC',4,'IV','PCUC/TJGO','Criptografia','PCUC/TJGO V1 — Instrumento Normativo Complementar IV','PLANO DE TRABALHO 5W2H + GANTT — Política de Criptografia e Uso de Recursos Criptográficos (PCUC/TJGO V1) — Instrumento Normativo Complementar IV da POSIC','#c026d3',false,'2026-07-01'),
('PGA',5,'V','PGA-TIC/TJGO','Gestão de Ativos de TIC','PGA-TIC/TJGO V1 — Instrumento Normativo Complementar V','PLANO DE TRABALHO 5W2H + GANTT — Política de Gestão de Ativos de TIC (PGA-TIC/TJGO V1) — Instrumento Normativo Complementar V da POSIC','#b45309',false,'2026-07-01'),
('PPINC',6,'VI','PPINC/TJGO','Prevenção a Incidentes Cibernéticos','PPINC/TJGO V2 — Instrumento Normativo Complementar VI','PLANO DE TRABALHO 5W2H + GANTT — Protocolo de Prevenção a Incidentes Cibernéticos (PPINC/TJGO V2) — Instrumento Normativo Complementar VI da POSIC','#dc2626',true,'2026-07-01'),
('PGCRC',7,'VII','PGCRC/TJGO','Gerenciamento de Crises Cibernéticas','PGCRC/TJGO V1 — Instrumento Normativo Complementar VII','PLANO DE TRABALHO 5W2H + GANTT — Protocolo de Gerenciamento de Crises Cibernéticas (PGCRC/TJGO V1) — Instrumento Normativo Complementar VII da POSIC','#9f1239',true,'2026-07-01'),
('PIILC',8,'VIII','PIILC-PJ/TJGO','Investigação de Ilícitos Cibernéticos','PIILC-PJ/TJGO V2 — Instrumento Normativo Complementar VIII','PLANO DE TRABALHO 5W2H + GANTT — Protocolo de Investigação para Ilícitos Cibernéticos (PIILC-PJ/TJGO V2) — Instrumento Normativo Complementar da POSIC','#4338ca',true,'2026-07-01'),
('PPIC',9,'IX','PPIC-Nuvem/TJGO','Infraestruturas Críticas e Nuvem','PPIC-Nuvem/TJGO V2 — Instrumento Normativo Complementar IX','PLANO DE TRABALHO 5W2H + GANTT — Política de Proteção de Infraestruturas Críticas de TIC e Serviços de Computação em Nuvem (PPIC-Nuvem/TJGO)','#ea580c',false,'2026-07-01'),
('PBRD',10,'X','PBRD/TJGO','Backup e Recuperação de Desastres','PBRD/TJGO — Instrumento Normativo Complementar X','PLANO DE TRABALHO 5W2H + GANTT — Política de Backup e Recuperação de Desastres (PBRD/TJGO) · Instrumento Normativo Complementar X da POSIC/TJGO','#059669',false,'2026-07-01'),
('PECC',11,'XI','PECC/TJGO','Educação e Cultura em Cibersegurança','PECC/TJGO V1 — Instrumento Normativo Complementar XI','PLANO DE TRABALHO 5W2H + GANTT — Política de Educação e Cultura em Cibersegurança (PECC/TJGO V1) — Instrumento Normativo Complementar XI da POSIC','#0d9488',false,'2026-07-01'),
('PSFT',12,'XII','PSFT/TJGO','Fornecedores e Terceiros','PSFT/TJGO V1 — Instrumento Normativo Complementar XII','PLANO DE TRABALHO 5W2H + GANTT — Política de Segurança da Informação no Relacionamento com Fornecedores e Terceiros (PSFT/TJGO V1) — Instrumento Normativo Complementar da POSIC','#65a30d',false,'2026-07-01'),
('PDSS',13,'XIII','PDSS/TJGO','Desenvolvimento Seguro de Software','PDSS/TJGO V1 — Instrumento Normativo Complementar XIII','PLANO DE TRABALHO 5W2H + GANTT — Política de Desenvolvimento Seguro de Software (PDSS-TJGO V1) — Instrumento Normativo Complementar XIII da POSIC/TJGO','#7e22ce',false,'2026-07-01')
ON CONFLICT (codigo) DO NOTHING;
