-- liquibase formatted sql

-- Seed REAL: 6 frameworks, 194 itens e 246 vínculos item↔instrumento. Idempotente.
-- Origem: SGSI/05_framework.sql. Tabelas prefixadas p/ sgsi_; subquery -> sgsi_framework_item.


-- changeset kaizen:227_seed_sgsi_framework splitStatements:false
INSERT INTO sgsi_framework (codigo,nome,descricao,ordem) VALUES
('CIS','CIS Controls v8.1','18 controles críticos de segurança do Center for Internet Security',1),
('NIST','NIST Cybersecurity Framework 2.0','Funções Govern, Identify, Protect, Detect, Respond e Recover (categorias)',2),
('ISO27001','ISO/IEC 27001:2022','Requisitos do SGSI — cláusulas 4 a 10',3),
('ISO27002','ISO/IEC 27002:2022','93 controles de segurança da informação (temas organizacional, pessoas, físico e tecnológico)',4),
('COBIT','COBIT 2019','40 objetivos de governança e gestão de I&T (EDM, APO, BAI, DSS, MEA)',5),
('LGPD','LGPD — Lei nº 13.709/2018','Obrigações estruturantes da Lei Geral de Proteção de Dados',6)
ON CONFLICT (codigo) DO NOTHING;


-- changeset kaizen:227b_seed_sgsi_framework_item splitStatements:false
INSERT INTO sgsi_framework_item (framework_codigo,item_id,nome,ordem) VALUES
('CIS','CIS 1','Inventário e Controle de Ativos Corporativos',1),
('CIS','CIS 2','Inventário e Controle de Ativos de Software',2),
('CIS','CIS 3','Proteção de Dados',3),
('CIS','CIS 4','Configuração Segura de Ativos e Software',4),
('CIS','CIS 5','Gestão de Contas',5),
('CIS','CIS 6','Gestão do Controle de Acessos',6),
('CIS','CIS 7','Gestão Contínua de Vulnerabilidades',7),
('CIS','CIS 8','Gestão de Logs de Auditoria',8),
('CIS','CIS 9','Proteções de E-mail e Navegador Web',9),
('CIS','CIS 10','Defesas contra Malware',10),
('CIS','CIS 11','Recuperação de Dados',11),
('CIS','CIS 12','Gestão da Infraestrutura de Rede',12),
('CIS','CIS 13','Monitoramento e Defesa da Rede',13),
('CIS','CIS 14','Conscientização sobre Segurança e Treinamento de Competências',14),
('CIS','CIS 15','Gestão de Provedores de Serviço',15),
('CIS','CIS 16','Segurança de Aplicações e Software',16),
('CIS','CIS 17','Gestão de Resposta a Incidentes',17),
('CIS','CIS 18','Testes de Invasão (Pentest)',18),
('NIST','GV.OC','Contexto Organizacional',1),
('NIST','GV.RM','Estratégia de Gestão de Riscos',2),
('NIST','GV.RR','Papéis, Responsabilidades e Autoridades',3),
('NIST','GV.PO','Política de Cibersegurança',4),
('NIST','GV.OV','Supervisão (Oversight)',5),
('NIST','GV.SC','Gestão de Riscos da Cadeia de Suprimentos',6),
('NIST','ID.AM','Gestão de Ativos',7),
('NIST','ID.RA','Avaliação de Riscos',8),
('NIST','ID.IM','Melhoria Contínua',9),
('NIST','PR.AA','Gestão de Identidades, Autenticação e Controle de Acesso',10),
('NIST','PR.AT','Conscientização e Treinamento',11),
('NIST','PR.DS','Segurança de Dados',12),
('NIST','PR.PS','Segurança de Plataformas',13),
('NIST','PR.IR','Resiliência da Infraestrutura Tecnológica',14),
('NIST','DE.CM','Monitoramento Contínuo',15),
('NIST','DE.AE','Análise de Eventos Adversos',16),
('NIST','RS.MA','Gestão de Incidentes (Resposta)',17),
('NIST','RS.AN','Análise de Incidentes',18),
('NIST','RS.CO','Comunicação de Resposta',19),
('NIST','RS.MI','Mitigação de Incidentes',20),
('NIST','RC.RP','Execução do Plano de Recuperação',21),
('NIST','RC.CO','Comunicação na Recuperação',22),
('ISO27001','Cláusula 4','Contexto da organização',1),
('ISO27001','Cláusula 5','Liderança e comprometimento',2),
('ISO27001','Cláusula 6','Planejamento (riscos, oportunidades e objetivos)',3),
('ISO27001','Cláusula 7','Apoio (recursos, competência, conscientização, comunicação, informação documentada)',4),
('ISO27001','Cláusula 8','Operação (planejamento, avaliação e tratamento de riscos)',5),
('ISO27001','Cláusula 9','Avaliação de desempenho (monitoramento, auditoria interna, análise crítica)',6),
('ISO27001','Cláusula 10','Melhoria contínua e não conformidades',7),
('ISO27002','5.1','Políticas de segurança da informação',1),
('ISO27002','5.2','Papéis e responsabilidades de SI',2),
('ISO27002','5.3','Segregação de funções',3),
('ISO27002','5.4','Responsabilidades da direção',4),
('ISO27002','5.5','Contato com autoridades',5),
('ISO27002','5.6','Contato com grupos de interesse especial',6),
('ISO27002','5.7','Inteligência de ameaças',7),
('ISO27002','5.8','SI na gestão de projetos',8),
('ISO27002','5.9','Inventário de informações e outros ativos',9),
('ISO27002','5.10','Uso aceitável de informações e ativos',10),
('ISO27002','5.11','Devolução de ativos',11),
('ISO27002','5.12','Classificação das informações',12),
('ISO27002','5.13','Rotulagem de informações',13),
('ISO27002','5.14','Transferência de informações',14),
('ISO27002','5.15','Controle de acesso',15),
('ISO27002','5.16','Gestão de identidade',16),
('ISO27002','5.17','Informações de autenticação',17),
('ISO27002','5.18','Direitos de acesso',18),
('ISO27002','5.19','SI nas relações com fornecedores',19),
('ISO27002','5.20','SI em acordos com fornecedores',20),
('ISO27002','5.21','Gestão de SI na cadeia de suprimentos de TIC',21),
('ISO27002','5.22','Monitoramento e gestão de mudanças de serviços de fornecedores',22),
('ISO27002','5.23','SI para uso de serviços em nuvem',23),
('ISO27002','5.24','Planejamento e preparação da gestão de incidentes',24),
('ISO27002','5.25','Avaliação e decisão sobre eventos de SI',25),
('ISO27002','5.26','Resposta a incidentes de SI',26),
('ISO27002','5.27','Aprendizado com incidentes de SI',27),
('ISO27002','5.28','Coleta de evidências',28),
('ISO27002','5.29','SI durante disrupção',29),
('ISO27002','5.30','Prontidão de TIC para continuidade de negócios',30),
('ISO27002','5.31','Requisitos legais, estatutários, regulamentares e contratuais',31),
('ISO27002','5.32','Direitos de propriedade intelectual',32),
('ISO27002','5.33','Proteção de registros',33),
('ISO27002','5.34','Privacidade e proteção de dados pessoais',34),
('ISO27002','5.35','Análise crítica independente da SI',35),
('ISO27002','5.36','Conformidade com políticas, regras e normas de SI',36),
('ISO27002','5.37','Procedimentos operacionais documentados',37),
('ISO27002','6.1','Triagem (screening)',38),
('ISO27002','6.2','Termos e condições de contratação',39),
('ISO27002','6.3','Conscientização, educação e treinamento em SI',40),
('ISO27002','6.4','Processo disciplinar',41),
('ISO27002','6.5','Responsabilidades após encerramento ou mudança da contratação',42),
('ISO27002','6.6','Acordos de confidencialidade (NDA)',43),
('ISO27002','6.7','Trabalho remoto',44),
('ISO27002','6.8','Relato de eventos de SI',45),
('ISO27002','7.1','Perímetros de segurança física',46),
('ISO27002','7.2','Entrada física',47),
('ISO27002','7.3','Segurança de escritórios, salas e instalações',48),
('ISO27002','7.4','Monitoramento de segurança física',49),
('ISO27002','7.5','Proteção contra ameaças físicas e ambientais',50),
('ISO27002','7.6','Trabalho em áreas seguras',51),
('ISO27002','7.7','Mesa limpa e tela limpa',52),
('ISO27002','7.8','Localização e proteção de equipamentos',53),
('ISO27002','7.9','Segurança de ativos fora das instalações',54),
('ISO27002','7.10','Mídias de armazenamento',55),
('ISO27002','7.11','Utilidades de apoio (energia, climatização)',56),
('ISO27002','7.12','Segurança do cabeamento',57),
('ISO27002','7.13','Manutenção de equipamentos',58),
('ISO27002','7.14','Descarte ou reutilização segura de equipamentos',59),
('ISO27002','8.1','Dispositivos endpoint do usuário',60),
('ISO27002','8.2','Direitos de acesso privilegiado',61),
('ISO27002','8.3','Restrição de acesso à informação',62),
('ISO27002','8.4','Acesso ao código-fonte',63),
('ISO27002','8.5','Autenticação segura',64),
('ISO27002','8.6','Gestão de capacidade',65),
('ISO27002','8.7','Proteção contra malware',66),
('ISO27002','8.8','Gestão de vulnerabilidades técnicas',67),
('ISO27002','8.9','Gestão de configuração',68),
('ISO27002','8.10','Exclusão de informações',69),
('ISO27002','8.11','Mascaramento de dados',70),
('ISO27002','8.12','Prevenção de vazamento de dados (DLP)',71),
('ISO27002','8.13','Backup das informações',72),
('ISO27002','8.14','Redundância de recursos de tratamento',73),
('ISO27002','8.15','Registro de eventos (log)',74),
('ISO27002','8.16','Atividades de monitoramento',75),
('ISO27002','8.17','Sincronização de relógios',76),
('ISO27002','8.18','Uso de programas utilitários privilegiados',77),
('ISO27002','8.19','Instalação de software em sistemas operacionais',78),
('ISO27002','8.20','Segurança de redes',79),
('ISO27002','8.21','Segurança de serviços de rede',80),
('ISO27002','8.22','Segregação de redes',81),
('ISO27002','8.23','Filtragem da web',82),
('ISO27002','8.24','Uso de criptografia',83),
('ISO27002','8.25','Ciclo de vida de desenvolvimento seguro',84),
('ISO27002','8.26','Requisitos de segurança de aplicações',85),
('ISO27002','8.27','Arquitetura de sistemas e princípios de engenharia segura',86),
('ISO27002','8.28','Codificação segura',87),
('ISO27002','8.29','Testes de segurança em desenvolvimento e aceitação',88),
('ISO27002','8.30','Desenvolvimento terceirizado',89),
('ISO27002','8.31','Separação de ambientes de desenvolvimento, teste e produção',90),
('ISO27002','8.32','Gestão de mudanças',91),
('ISO27002','8.33','Informações de teste',92),
('ISO27002','8.34','Proteção de sistemas durante testes de auditoria',93),
('COBIT','EDM01','Estrutura de governança definida e mantida',1),
('COBIT','EDM02','Entrega de benefícios',2),
('COBIT','EDM03','Otimização de risco',3),
('COBIT','EDM04','Otimização de recursos',4),
('COBIT','EDM05','Engajamento das partes interessadas',5),
('COBIT','APO01','Estrutura de gestão de I&T',6),
('COBIT','APO02','Estratégia',7),
('COBIT','APO03','Arquitetura corporativa',8),
('COBIT','APO04','Inovação',9),
('COBIT','APO05','Portfólio',10),
('COBIT','APO06','Orçamento e custos',11),
('COBIT','APO07','Recursos humanos',12),
('COBIT','APO08','Relacionamentos',13),
('COBIT','APO09','Acordos de serviço',14),
('COBIT','APO10','Fornecedores',15),
('COBIT','APO11','Qualidade',16),
('COBIT','APO12','Risco',17),
('COBIT','APO13','Segurança da informação',18),
('COBIT','APO14','Dados',19),
('COBIT','BAI01','Programas',20),
('COBIT','BAI02','Definição de requisitos',21),
('COBIT','BAI03','Identificação e construção de soluções',22),
('COBIT','BAI04','Disponibilidade e capacidade',23),
('COBIT','BAI05','Mudança organizacional',24),
('COBIT','BAI06','Mudanças de TI',25),
('COBIT','BAI07','Aceitação e transição de mudanças de TI',26),
('COBIT','BAI08','Conhecimento',27),
('COBIT','BAI09','Ativos',28),
('COBIT','BAI10','Configuração',29),
('COBIT','BAI11','Projetos',30),
('COBIT','DSS01','Operações',31),
('COBIT','DSS02','Requisições de serviço e incidentes',32),
('COBIT','DSS03','Problemas',33),
('COBIT','DSS04','Continuidade',34),
('COBIT','DSS05','Serviços de segurança',35),
('COBIT','DSS06','Controles de processos de negócio',36),
('COBIT','MEA01','Monitoramento de desempenho e conformidade',37),
('COBIT','MEA02','Sistema de controles internos',38),
('COBIT','MEA03','Conformidade com requisitos externos',39),
('COBIT','MEA04','Auditoria (assurance)',40),
('LGPD','Art. 6º','Princípios do tratamento de dados pessoais',1),
('LGPD','Art. 7º/11','Bases legais para o tratamento (inclusive dados sensíveis)',2),
('LGPD','Art. 14','Tratamento de dados de crianças e adolescentes',3),
('LGPD','Art. 15/16','Término do tratamento e eliminação de dados',4),
('LGPD','Art. 18','Direitos dos titulares (acesso, correção, eliminação, portabilidade)',5),
('LGPD','Art. 33','Transferência internacional de dados',6),
('LGPD','Art. 37','Registro das operações de tratamento (RAT)',7),
('LGPD','Art. 38','Relatório de Impacto à Proteção de Dados (RIPD)',8),
('LGPD','Art. 39','Instruções do controlador ao operador',9),
('LGPD','Art. 41','Encarregado pelo tratamento de dados (DPO)',10),
('LGPD','Art. 46','Medidas de segurança técnicas e administrativas',11),
('LGPD','Art. 46 §2º / 49','Privacidade desde a concepção (privacy by design)',12),
('LGPD','Art. 48','Comunicação de incidentes à ANPD e aos titulares',13),
('LGPD','Art. 50','Boas práticas e governança (programa de privacidade)',14)
ON CONFLICT (framework_codigo,item_id) DO NOTHING;


-- changeset kaizen:227c_seed_sgsi_framework_item_instrumento splitStatements:false
INSERT INTO sgsi_framework_item_instrumento (framework_item_id,instrumento_codigo)
VALUES
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 1'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 2'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 2'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 3'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 3'),'PCUC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 4'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 4'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 5'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 6'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 7'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 8'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 8'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 9'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 9'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 10'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 10'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 11'),'PBRD'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 12'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 13'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 13'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 14'),'PECC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 15'),'PSFT'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 15'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 16'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 17'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 17'),'PGCRC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 18'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='CIS' AND item_id='CIS 18'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='GV.OC'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='GV.RM'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='GV.RR'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='GV.PO'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='GV.OV'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='GV.SC'),'PSFT'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='ID.AM'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='ID.RA'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='ID.RA'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='ID.IM'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='PR.AA'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='PR.AT'),'PECC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='PR.DS'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='PR.DS'),'PCUC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='PR.DS'),'PBRD'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='PR.PS'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='PR.PS'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='PR.PS'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='PR.IR'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='PR.IR'),'PBRD'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='DE.CM'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='DE.AE'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='RS.MA'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='RS.MA'),'PGCRC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='RS.AN'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='RS.AN'),'PIILC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='RS.CO'),'PGCRC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='RS.MI'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='RS.MI'),'PGCRC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='RC.RP'),'PBRD'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='RC.RP'),'PGCRC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='NIST' AND item_id='RC.CO'),'PGCRC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27001' AND item_id='Cláusula 4'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27001' AND item_id='Cláusula 5'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27001' AND item_id='Cláusula 6'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27001' AND item_id='Cláusula 7'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27001' AND item_id='Cláusula 7'),'PECC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27001' AND item_id='Cláusula 8'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27001' AND item_id='Cláusula 9'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27001' AND item_id='Cláusula 10'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.1'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.2'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.3'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.3'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.4'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.5'),'PGCRC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.5'),'PIILC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.6'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.7'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.8'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.9'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.10'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.11'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.11'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.12'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.13'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.14'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.14'),'PCUC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.15'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.16'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.17'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.18'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.19'),'PSFT'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.20'),'PSFT'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.21'),'PSFT'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.22'),'PSFT'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.23'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.24'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.25'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.26'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.26'),'PGCRC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.27'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.28'),'PIILC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.29'),'PGCRC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.29'),'PBRD'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.30'),'PBRD'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.30'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.31'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.32'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.32'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.33'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.34'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.34'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.35'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.36'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='5.37'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='6.1'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='6.2'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='6.3'),'PECC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='6.4'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='6.4'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='6.5'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='6.6'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='6.6'),'PSFT'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='6.7'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='6.7'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='6.8'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.1'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.2'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.3'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.4'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.4'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.5'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.6'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.7'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.7'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.8'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.9'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.9'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.10'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.10'),'PCUC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.11'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.12'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.13'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='7.14'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.1'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.1'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.2'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.3'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.3'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.4'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.4'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.5'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.6'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.7'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.7'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.8'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.9'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.9'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.10'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.10'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.11'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.11'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.12'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.12'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.13'),'PBRD'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.14'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.15'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.15'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.16'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.17'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.18'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.19'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.19'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.20'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.21'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.22'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.23'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.24'),'PCUC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.25'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.26'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.27'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.28'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.29'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.30'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.30'),'PSFT'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.31'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.32'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.32'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.33'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='ISO27002' AND item_id='8.34'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='EDM01'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='EDM03'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='EDM05'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='APO01'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='APO02'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='APO03'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='APO07'),'PECC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='APO09'),'PSFT'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='APO10'),'PSFT'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='APO12'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='APO13'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='APO14'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='BAI02'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='BAI03'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='BAI04'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='BAI06'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='BAI06'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='BAI07'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='BAI09'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='BAI10'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='DSS01'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='DSS02'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='DSS03'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='DSS04'),'PBRD'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='DSS04'),'PGCRC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='DSS05'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='DSS05'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='DSS06'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='MEA01'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='MEA02'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='MEA03'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='COBIT' AND item_id='MEA04'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 6º'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 6º'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 7º/11'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 7º/11'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 14'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 15/16'),'PGA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 15/16'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 18'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 33'),'PPIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 33'),'PSFT'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 37'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 37'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 38'),'PUA'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 38'),'PCI'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 39'),'PSFT'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 41'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 46'),'PCUC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 46'),'IAM'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 46'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 46 §2º / 49'),'PDSS'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 48'),'PPINC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 48'),'PGCRC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 48'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 50'),'POSIC'),
((SELECT id FROM sgsi_framework_item WHERE framework_codigo='LGPD' AND item_id='Art. 50'),'PECC')
ON CONFLICT DO NOTHING;
