-- =====================================================================
-- Povoar o cadastro de Ações do PDTIC (tabela pdtic_acoes) — PRODUÇÃO
-- Fonte: PDTIC 2025-2027 (Versão 2), "9.1 Ações Gerais sem custo" (AG01..AG82).
-- =====================================================================
--
-- Fala, equipe! Esse script só INSERE as ações do quadro do PDTIC no cadastro.
-- É aditivo (nada de UPDATE/DELETE) e IDEMPOTENTE: se rodar de novo, ele pula
-- as ações que já existem (checa por id_pdtic). Pode rodar tranquilo.
--
-- Observações do mapeamento:
--   * diretoria  = sigla da 1ª parte do "PROPRIETÁRIO" (antes da "/"), EXCETO:
--       - "Secretaria de Governança Judiciária e Tecnológica / CGP"         -> GEJUT
--       - "Diretoria de Infraestrutura em Tecnologia da Informação / CCA"   -> GEJUT
--     Demais siglas: DITI, DSTI, SGJT, CSTI (por extenso no doc).
--   * area_responsavel = em branco (NULL) — será preenchida manualmente depois.
--   * conclusao = valor literal do doc ("Concluída" ou "Mmm/AAAA").
--
-- Pré-requisito: migration 216 aplicada (colunas de detalhe do PDTIC).
-- =====================================================================

BEGIN;

INSERT INTO pdtic_acoes
    (id_pdtic, nome, diretoria, area_responsavel, conclusao,
     necessidade_identificada, resultado, reagendada, classe, indicador,
     objetivos_enticjud, macrodesafios_tjgo)
SELECT v.id_pdtic, v.nome, v.diretoria, NULL, v.conclusao,
       v.necessidade, v.resultado, v.reagendada, v.classe, v.indicador,
       v.objetivos, v.macrodesafios
FROM (VALUES
  ('AG01', 'Desenvolver ferramenta para coleta das Ações Planejadas do PDTIC', 'GEJUT', 'Concluída',
   'Simplificar o recebimento de proposta das ações planejadas, com e sem custo, por parte das unidades de envolvidas no desenvolvimento do Plano Diretor de TIC, de forma a otimizar a construção do quadro de ações do PDTIC.',
   'Sistema web em formato de formulário para apoiar no levantamento e planejamento das ações do PDTIC', 'Não', 'PRIN', 'KR1', 'ON02, ON05', 'MACRO12 e MACRO18'),
  ('AG02', 'Disponibilizar no site do TJGO o Plano de Contratação Anual de TIC - ano 2025', 'GEJUT', 'Concluída',
   'Manter o Plano de Contratação Anual de TIC atualizado, disponível e em local de fácil acesso no site do TJGO.',
   'Documento publicado no Portal de Governança de TIC do TJGO.', 'Não', 'PRIN', 'KR1, KR2', 'ON05, ON06', 'MACRO12 e MACRO18'),
  ('AG03', 'Aprovar o Plano de Diretor de Tecnologia da Informação e Comunicação – PDTIC', 'GEJUT', 'Concluída',
   'Aprovar o PDTIC no Comite de Governança de TIC do órgão, conforme determinação da Resolução nº 370/2021 do CNJ.',
   'PDTIC aprovado e publicado no Portal de Governança de TIC do órgão', 'Não', 'PRIN', 'KR1, KR3', 'ON01, ON05', 'MACRO12 e MACRO18'),
  ('AG04', 'Estabelecer matriz de cursos e treinamentos do Plano de Capacitação de TIC', 'GEJUT', 'Concluída',
   'Documentar os cursos e treinamentos técnicos apresentados pelos Macroprocessos de TIC em consonância com a Presidência do TJGO – no estabelecimento do Plano de Capacitação de TIC da instituição.',
   'Documento com todos os cursos e treinamentos solicitados pela área de Tecnologia da Informação do TJGO.', 'Não', 'PRIN', 'KR1', 'ON03, ON05', 'MACRO12 e MACRO18'),
  ('AG05', 'Disponibilizar no site do TJGO o Painel de Controle Orçamentário de TIC - ano 2025', 'GEJUT', 'Concluída',
   'Disponibilizar ferramenta para acompanhamento da execução orçamentária do Plano de Contratações Anual de Tecnologia da Informação e Comunicação no Portal de Governança de TIC no site do TJGO.',
   'Painel de acompanhamento do status das contratações do Plano de Contratações Anual de Tecnologia da Informação e Comunicação disponível no Portal da Governança de TIC.', 'Não', 'PRIN', 'KR1, KR2', 'ON01, ON05, ON06', 'MACRO12 e MACRO18'),
  ('AG06', 'Atualizar o Plano de Ação iGovTIC-JUD 2021/2026', 'GEJUT', 'Concluída',
   'Assegurar a atualização do 4º monitoramento Plano de Ação iGovTIC em atendimento as recomendações da Resolução nº 370/2021 do CNJ e, conforme as novas orientações a partir do questionário de levantamento do iGovTIC-JUD em 2022. O referido plano de ação é monitorado por todos interessados através do PROAD 314505.',
   'Plano de Ação iGovTIC-JUD atualizado no PROAD 314505', 'Não', 'PRIN', 'KR1', 'ON05', 'MACRO12 e MACRO18'),
  ('AG07', 'Implantar o painel de execução (Portal de Governança de TIC) e visual (BI - Transparência) do PDTIC e PCTIC', 'GEJUT', 'Concluída',
   'Disponibilizar ferramenta para acompanhamento da execução das ações planejadas e treinamentos do Plano Diretor e de Capacitação - 2025/2027, das áreas de Tecnologia da Informação, no Portal de Governança de TIC disponível no site do TJGO.',
   'Painéis de acompanhamento do status das ações planejadas e treinamentos do PDTIC e PCTIC disponíveis no Portal da Governança de TIC.', 'Não', 'PRIN', 'KR1', 'ON02, ON05', 'MACRO12 e MACRO18'),
  ('AG08', 'Revisar normativo de competências para recursos humanos de TIC', 'GEJUT', 'Concluída',
   'Atualizar os critérios objetivos das competências gerenciais e técnicas para a escolha de líderes ocupantes das funções de Direção e Coordenação das unidades que compõem a área de TIC do Poder Judiciário Goiano.',
   'Documento publicado no Portal de Governança de TIC do TJGO.', 'AG052 2023/25', 'PRIN', 'KR1, KR3', 'ON03, ON05', 'MACRO12 e MACRO18'),
  ('AG09', 'Promover a simplificação das decisões em processos judiciais, utilizando inteligência artificial, nos processos previdenciários, família e em juizados — Visual Law', 'SGJT', 'Concluída',
   'Tornar as decisões mais claras e acessíveis, reduzindo a complexidade jurídica para facilitar o entendimento por parte dos cidadãos.',
   'Maior transparência, padronização e efetividade na comunicação das decisões, contribuindo para a satisfação dos usuários.', 'Não', 'SIS', 'KR1', 'ON01', 'MACRO12 e MACRO18'),
  ('AG10', 'Implementar o uso de inteligência artificial generativa para aprimorar a atividade-fim e administrativa do Tribunal de Justiça – AGAIA', 'SGJT', 'Concluída',
   'Modernizar e otimizar processos, reduzindo a carga de trabalho manual e oferecendo suporte inteligente a magistrados e servidores.',
   'Maior produtividade, redução do tempo de tramitação processual e suporte mais avançado na elaboração de peças e na execução de atividades administrativas.', 'Não', 'SIS', 'KR1', 'ON02', 'MACRO12 e MACRO18'),
  ('AG11', 'Realizar estudo técnico de modelo de série temporal para identificar tendências e casos novos', 'SGJT', 'Concluída',
   'Prever o volume futuro de processos e adequar recursos (humanos e materiais) para otimizar o atendimento da demanda e evitar sobrecargas.',
   'Planejamento mais eficiente dos recursos, redução de gargalos e melhoria contínua do fluxo de trabalho, contribuindo para a agilidade e a qualidade dos serviços prestados.', 'Não', 'PRIN', 'KR1', 'ON05', 'MACRO12 e MACRO18'),
  ('AG12', 'Revisar normativo de metas e diretrizes para recursos humanos de TIC', 'GEJUT', 'Concluída',
   'Atualizar metas específicas e diretrizes de desempenho para os recursos humanos que compõem a área de TIC, aperfeiçoando quando necessário os critérios de produtividades exigidos aos servidores lotados na SGJT.',
   'Documento publicado no Portal de Governança de TIC do TJGO.', 'AG053 2023/25', 'PRIN', 'KR1, KR3', 'ON05', 'MACRO12 e MACRO18'),
  ('AG13', 'Publicitar o Plano de Capacitação do TJGO', 'GEJUT', 'Concluída',
   'Manter atualizado o Plano de Capacitação do TJGO para o biênio vigente, disponível em local de fácil acesso na internet do órgão, no Portal de Governança de TIC no site do TJGO. Esse plano será estabelecido pela Presidência do TJGO.',
   'Plano de Capacitação publicado no Portal de Governança de TIC do TJGO.', 'Não', 'PRIN', 'KR1', 'ON02, ON03, ON05', 'MACRO12 e MACRO18'),
  ('AG14', 'Preparar as respostas para o questionário anual da ENTIC-JUD/2025', 'GEJUT', 'Concluída',
   'Acompanhar junto às unidades gestoras do TJGO a preparação do preenchimento do questionário, para o ano de 2025, da Estratégia Nacional de Tecnologia da Informação e Comunicações acerca do levantamento de governança, gestão e infraestrutura do Poder Judiciário Nacional, índice iGovTIC-JUD (Resolução nº 370/2021-CNJ).',
   'Espelho das respostas que serão submetidas no questionário oficial do CNJ', 'Não', 'PRIN', 'KR1', 'ON05', 'MACRO12 e MACRO18'),
  ('AG15', 'Propor a revisão da análise de rotatividade de recursos humanos de TIC', 'GEJUT', 'Jun/2025',
   'Participar de forma colaborativa com a Diretoria de Gestão de Pessoas no projeto de análise de rotatividade de pessoal com o objetivo de reduzir a evasão de servidores de TIC do quadro permanente para atendimento das recomendações da Resolução nº 370/2021 do CNJ.',
   'Documento com os resultados da análise publicado no Portal de Governança de TIC do TJGO.', 'Não', 'PRIN', 'KR1', 'ON05', 'MACRO12 e MACRO18'),
  ('AG16', 'Revisar o processo de Planejamento de Aquisições e de Contratações de Soluções de TIC', 'GEJUT', 'Concluída',
   'Revisar o processo de Planejamento de Aquisições e de Contratações de Soluções de TIC, registrado no Proad 202406000528823, em atenção à Resolução nº 468/2022 do CNJ, bem como à Lei de Licitações e Contratos Administrativos nº 14.133/2021.',
   'Processo de Planejamento de Aquisições e de Contratações de Soluções de TIC revisado, aprimorado, padronizado e aprovado.', 'Não', 'PRIN', 'KR1, KR2, KR3', 'ON05, ON06', 'MACRO12 e MACRO18'),
  ('AG17', 'Revisar o processo de Gerenciamento de Contratos de TIC', 'GEJUT', 'Concluída',
   'Revisar o processo de Gerenciamento de Contratos de TIC, registrado no Proad 202406000528810, em atenção à Resolução nº 468/2022 do CNJ, bem como à Lei de Licitações e Contratos Administrativos nº 14.133/2021.',
   'Processo de Gerenciamento de Contratos de TIC revisado, aprimorado, padronizado e aprovado.', 'Não', 'PRIN', 'KR1, KR2, KR3', 'ON05, ON06', 'MACRO12 e MACRO18'),
  ('AG18', 'Revisar o processo de Planejamento Orçamentário de TIC', 'GEJUT', 'Concluída',
   'Revisar o Processo de Planejamento Orçamentário de TIC, registrado no Proad 202407000539342, em atenção à Resolução nº 468/2022 do CNJ, bem como à Lei de Licitações e Contratos Administrativos nº 14.133/2021, da Presidência da República.',
   'Processo de Planejamento Orçamentário de TIC revisado, padronizado e aprovado.', 'Não', 'PRIN', 'KR1, KR2, KR3', 'ON05, ON06', 'MACRO12 e MACRO18'),
  ('AG19', 'Implementar monitoramento automatizado da atualização dos painéis de BI de Gestão Administrativa', 'SGJT', 'Concluída',
   'Atualmente, não há um mecanismo eficiente para acompanhar a atualização dos painéis de Business Intelligence (BI) de Gestão Administrativa, o que pode resultar em dados desatualizados e impactar a tomada de decisão. A implementação de um monitoramento automatizado é essencial para garantir a integridade e a confiabilidade das informações disponibilizadas.',
   'Gestão mais eficiente e confiante nas informações utilizadas para análise e tomada de decisão.', 'Não', 'SIS', 'KR1', 'ON02, ON05', 'MACRO12 e MACRO18'),
  ('AG20', 'Revisar o Plano de Trabalho sexenal da Resolução nº 370/2021-CNJ', 'GEJUT', 'Concluída',
   'Participar de forma colaborativa com a Diretoria de Planejamento e Inovação, na revisão anual do plano de trabalho sexenal, que acontecerá em 2025 e deverá ser apresentado ao Conselho Nacional de Justiça, contendo ações do TJGO para atendimento das recomendações da Resolução nº 370/2021 do CNJ.',
   'Plano de Trabalho Sexenal da Resolução nº 370/2021-CNJ devidamente revisado e submetido ao CNJ.', 'Não', 'PRIN', 'KR1', 'ON05', 'MACRO12 e MACRO18'),
  ('AG21', 'Evoluir a Berna Inteligência Artificial para automatizar atos ordinatórios, movimentações padrões e outros.', 'SGJT', 'Concluída',
   'Agilizar a triagem de processos que compartilham aspectos semelhantes, evitando esforços repetitivos e possibilitando julgamentos em bloco.',
   'Redução do tempo de análise, maior uniformidade nas decisões e otimização do fluxo processual, contribuindo para uma prestação jurisdicional mais célere.', 'Não', 'SIS', 'KR1', 'ON02, ON07', 'MACRO12 e MACRO18'),
  ('AG22', 'Adequar os paineis às novas regras do prêmio CNJ', 'SGJT', 'Concluída',
   'Atender as exigências e critérios definidos pelo Conselho Nacional de Justiça (CNJ) para participação e reconhecimento em premiações.',
   'Conformidade com as normas do CNJ, favorecendo a competitividade e o reconhecimento do Tribunal em premiações, além de assegurar a melhoria contínua de processos.', 'Não', 'SIS', 'KR1', 'ON07', 'MACRO12 e MACRO18'),
  ('AG23', 'Promover o acesso à linguagem simples e perguntas frequentes por meio de ferramenta de Chat Bot.', 'SGJT', 'Concluída',
   'Oferecer atendimento ágil e objetivo aos cidadãos, possibilitando respostas imediatas às dúvidas mais comuns e reduzindo o atendimento presencial ou telefônico.',
   'Aumento na satisfação do público, com redução de filas e maior disponibilidade de informações, otimizando o relacionamento entre o Tribunal e os usuários.', 'Não', 'SIS', 'KR1', 'ON01', 'MACRO12 e MACRO18'),
  ('AG24', 'Manter e atualizar o painel de estatísticas do DATAJUD – CNJ', 'SGJT', 'Concluída',
   'Fornecer estatísticas consistentes e atualizadas sobre o andamento processual, auxiliando a gestão estratégica e a transparência das informações judiciais.',
   'Maior confiabilidade dos dados estatísticos, permitindo análise aprofundada dos indicadores e melhor embasamento para decisões gerenciais e estratégicas.', 'Não', 'SIS', 'KR1', 'ON07', 'MACRO12 e MACRO18'),
  ('AG25', 'Implementar sistema de monitoramento de advogados e notas técnicas, para atender o centro de inteligência, utilizando IA.', 'SGJT', 'Concluída',
   'Prevenir práticas abusivas ou antijurídicas, garantindo maior segurança e confiabilidade no sistema judicial.',
   'Detecção e prevenção pró-ativa de demandas irregulares, garantindo a integridade dos processos e protegendo a credibilidade do Poder Judiciário.', 'Não', 'SIS', 'KR1', 'ON07', 'MACRO12 e MACRO18'),
  ('AG26', 'Utilizar soluções de IA e LLM para automatizar a identificação, controle e a fiscalização financeira.', 'SGJT', 'Concluída',
   'Otimizar a arrecadação, reduzindo a inadimplência e garantindo maior eficiência na gestão financeira do Poder Judiciário.',
   'Diminuição de perdas financeiras, com automatização da cobrança e aprimoramento no controle de custas, resultando em maior transparência e eficiência na gestão de receitas.', 'Não', 'SIS', 'KR1', 'ON01, ON07', 'MACRO12 e MACRO18'),
  ('AG27', 'Revisar repositório no Portal de Governança de TIC', 'GEJUT', 'Concluída',
   'Manter a transparência do histórico da documentação de TIC, quanto aos planejamentos, processos, normativas e entre outros, no sítio eletrônico do Poder Judiciário do Estado de Goiás.',
   'Submenu no Portal de Governança de TIC do TJGO contendo histórico das evidências de Governança.', 'Não', 'PRIN', 'KR1', 'ON02, ON05', 'MACRO12 e MACRO18'),
  ('AG28', 'Atualizar o Painel Visual de TIC disponível no Portal de Governança de TIC do TJGO', 'GEJUT', 'Concluída',
   'Disponibilizar atualizações do painel visual em BI buscando inovação de forma colaborativa dos projetos e ações da área de Tecnologia da Informação e Comunicação da Presidência.',
   'Painel Visual de TIC atualizado e disponível no Portal da Transparência e de Governança de TIC do TJGO', 'Não', 'PRIN', 'KR1', 'ON01, ON02, ON04, ON05', 'MACRO12 e MACRO18'),
  ('AG29', 'Aprimorar os sistemas de armazenamento onde estão os documentos dos servidores e magistrados do TJGO', 'DITI', 'Out/2026',
   'Aperfeiçoar o gerencimento e otimizar o tempo de resposta no acesso e busca aos arquivos e documentos armazenados nos computadores servidores do TJGO.',
   'Ambiente de armazenamento dos documentos dos servidores e magistrados do TJGO com controle de segurança mais robusto, bem como maior potencial de escalabilidade e resposta ágil nos acessos.', 'Não', 'INFRA', 'KR1', 'ON01, ON07', 'MACRO12 e MACRO18'),
  ('AG30', 'Propor atualização na Resolução de Recursos Humanos de TIC', 'GEJUT', 'Out/2026',
   'Atualizar quanto às normativas de competências e metas de recursos humanos a Política de Gestão de Pessoas de TIC no âmbito do Poder Judiciário do Estado de Goiás.',
   'Política de Gestão de Pessoas de TIC no âmbito do Poder Judiciário do Estado de Goiás atualizada com referência aos atuais normativos.', 'AG046 2023/25', 'PRIN', 'KR1, KR3', 'ON01, ON03, ON05', 'MACRO12 e MACRO18'),
  ('AG31', 'Revisar e aprimorar os procedimentos de trabalho na Coordenadoria de Infraestrutura Tecnológica (CITEC)', 'DITI', 'Concluída',
   'Garantir a padronização, disponibilidade, continuidade e retenção de conhecimento dos serviços oferecidos na Coordenadoria de Infraestrutura Tecnológica (CITEC), por meio da formalização e melhoria contínua dos processos de trabalho.',
   'Processos de trabalho padronizados, formalizados e atualizados na Coordenadoria de Infraestrutura Tecnológica (CITEC).', 'Não', 'INFRA', 'KR1', 'ON05, ON06', 'MACRO12 e MACRO18'),
  ('AG32', 'Estabelecer o Processo de Planejamento Tático Operacional (PDTIC)', 'GEJUT', 'Concluída',
   'Instituir formalmente como norma de cumprimento obrigatório o desenvolvimento do Plano Diretor de Tecnologia da Informação e Comunicação no âmbito do TJGO.',
   'Processo de Negócio aprovado e publicado no Portal de Governança de TIC', 'AG045 2023/25', 'PRIN', 'KR1, KR3', 'ON05', 'MACRO12 e MACRO18'),
  ('AG33', 'Revisar e aprimorar os procedimentos de trabalho na Coordenadoria de Suporte em Tecnologia da Informação (CSTI)', 'DITI', 'Concluída',
   'Garantir a padronização, disponibilidade, continuidade e retenção de conhecimento dos serviços oferecidos na Coordenadoria de Suporte em Tecnologia da Informação (CSTI), por meio da formalização e melhoria contínua dos processos de trabalho.',
   'Processos de trabalho padronizados, formalizados e atualizados na Coordenadoria de Suporte em Tecnologia da Informação (CSTI).', 'Não', 'PRIN', 'KR1', 'ON05', 'MACRO12 e MACRO18'),
  ('AG34', 'Automatizar os relatórios da Gestão Orçamentária e Financeira no Portal da Transparência do TJGO', 'SGJT', 'Concluída',
   'Atualmente, a geração e publicação dos relatórios de gestão orçamentária e financeira no Portal da Transparência são realizadas de forma manual, o que demanda tempo, está sujeita a erros operacionais e pode resultar em atrasos na disponibilização das informações. A automação desse processo é necessária para garantir maior eficiência, confiabilidade e conformidade com os requisitos de transparência pública.',
   'Relatórios gerados e publicados de forma automatizada, com redução do tempo de processamento e minimização de erros manuais, garantindo que as informações estejam sempre atualizadas e acessíveis ao público e em conformidade com as exigências legais e institucional.', 'Não', 'SIS', 'KR1', 'ON02', 'MACRO12 e MACRO18'),
  ('AG35', 'Implantar painel de indicadores dos Processos de Negócio de TIC', 'GEJUT', 'Concluída',
   'Disponibilizar os indicadores de monitoramento para acompanhamento quanto à revisão nos processos de negócios dos macroprocessos de TIC no Portal de Governança de TIC do site do TJGO.',
   'Painel de indicadores de desempenho dos processos de gestão de serviços de TIC conforme definição da unidade gestora do referido processo de negócio.', 'AG044 23/25', 'PRIN', 'KR1', 'ON01, ON02, ON05', 'MACRO12 e MACRO18'),
  ('AG36', 'Revisar o Plano de Diretor de Tecnologia da Informação e Comunicação – PDTIC', 'GEJUT', 'Jan/2026',
   'Preparar documento de revisão obrigatória, programada para janeiro de 2026, do Plano Diretor de Tecnologia da Informação e Comunicações do TJGO – biênio 2025/27.',
   'Documento de revisão do Plano Diretor de TIC aprovado e publicado no Portal de Governança de TIC do TJGO.', 'Não', 'PRIN', 'KR1, KR3', 'ON01, ON05', 'MACRO12 e MACRO18'),
  ('AG37', 'Disponibilizar no site do TJGO o Plano de Contratação Anual de TIC - ano 2026', 'GEJUT', 'Concluída',
   'Manter o Plano de Contratação Anual de TIC atualizado, disponível e em local de fácil acesso no site do TJGO.',
   'Documento publicado no Portal de Governança de TIC do TJGO.', 'Não', 'PRIN', 'KR1, KR2', 'ON05, ON06', 'MACRO12 e MACRO18'),
  ('AG38', 'Disponibilizar no site do TJGO o Painel de Controle Orçamentário de TIC - ano 2026', 'GEJUT', 'Concluída',
   'Disponibilizar ferramenta para acompanhamento da execução orçamentária do Plano de Contratações Anual de Tecnologia da Informação e Comunicação no Portal de Governança de TIC no site do TJGO.',
   'Painel de acompanhamento do status das contratações do Plano de Contratações Anual de Tecnologia da Informação e Comunicação disponível no Portal da Governança de TIC.', 'Não', 'PRIN', 'KR1, KR2', 'ON01, ON05, ON06', 'MACRO12 e MACRO18'),
  ('AG39', 'Desenvolver sistema de Gestão de Frotas', 'SGJT', 'Abr/2026',
   'O controle da frota de veículos é realizado de forma descentralizada e com uso de processos manuais, o que pode gerar inconsistências nos registros, dificuldades no monitoramento da utilização e manutenção dos veículos, além de impacto na eficiência operacional e nos custos. Um sistema específico é necessário para aprimorar a gestão, garantindo maior controle e transparência.',
   'Solução implantada de gerenciamento automatizado da frota, incluindo controle de uso, manutenção preventiva, consumo de combustível e alocação dos veículos, o que resultará em maior eficiência na gestão, redução de custos operacionais, melhor planejamento logístico e maior transparência nas operações.', 'Não', 'SIS', 'KR1', 'ON02, ON05', 'MACRO12 e MACRO18'),
  ('AG40', 'Atualizar o Plano de Ação iGovTIC-JUD 2021/2026', 'GEJUT', 'Concluída',
   'Assegurar a atualização do 5º monitoramento Plano de Ação iGovTIC em atendimento as recomendações da Resolução nº 370/2021 do CNJ e, conforme as novas orientações a partir do questionário de levantamento do iGovTIC-JUD em 2022. O referido plano de ação é monitorado por todos por todos interessados através do PROAD 314505.',
   'Plano de Ação iGovTIC-JUD atualizado no PROAD 314505', 'Não', 'PRIN', 'KR1', 'ON05', 'MACRO12 e MACRO18'),
  ('AG41', 'Revisar o Plano de Trabalho sexenal da Resolução nº 370/2021 do CNJ', 'GEJUT', 'Mai/2026',
   'Participar de forma colaborativa com a Diretoria de Planejamento e Inovação, na revisão anual do plano de trabalho sexenal, que acontecerá em 2026 e deverá ser apresentado ao Conselho Nacional de Justiça, contendo ações do TJGO para atendimento das recomendações da Resolução nº 370/2021 do CNJ.',
   'Plano de Trabalho Sexenal da Resolução nº 370/2021-CNJ devidamente revisado e submetido ao CNJ.', 'Não', 'PRIN', 'KR1', 'ON05', 'MACRO12 e MACRO18'),
  ('AG42', 'Preparar as respostas para o questionário anual da ENTIC-JUD/2026', 'GEJUT', 'Jun/2026',
   'Acompanhar junto às unidades gestoras do TJGO a preparação do preenchimento do questionário, para o ano de 2026, da Estratégia Nacional de Tecnologia da Informação e Comunicações acerca do levantamento de governança, gestão e infraestrutura do Poder Judiciário Nacional, índice iGovTIC-JUD (Resolução nº 370/2021-CNJ).',
   'Espelho das respostas que serão submetidas no questionário oficial do CNJ', 'Não', 'PRIN', 'KR1', 'ON05', 'MACRO12 e MACRO18'),
  ('AG43', 'Implementar sistema para Gestão do Parcelamento de Débitos Administrativos dos Servidores do TJGO', 'SGJT', 'Ago/2026',
   'O processo de parcelamento de débitos administrativos dos servidores é realizado de forma manual, o que pode gerar morosidade, erros no cálculo das parcelas e dificuldades no acompanhamento dos pagamentos. A falta de um sistema específico compromete a transparência e a eficiência na gestão desses débitos.',
   'Sistema implantado com automatização do processo de parcelamento de débitos administrativos, o que promoverá maior agilidade, precisão nos valores e transparência nos cálculos, concessões e acompanhamento dos parcelamentos, que, por consequência, resultará em uma gestão mais eficiente, com menos erros operacionais e mais comodidade aos servidores', 'Não', 'SIS', 'KR1', 'ON02, ON05', 'MACRO12 e MACRO18'),
  ('AG44', 'Implantar projeto de identificação biométrica do Conselho Nacional de Justiça (CNJ) no sistema prisional do Estado de Goiás', 'DITI', 'Dez/2026',
   'Identificar e controlar a população carcerária do Estado de Goiás.',
   'Segurança e transparência no controle da população carcerária.', 'Não', 'SUP', 'KR1', 'ON02', 'MACRO12 e MACRO18'),
  ('AG45', 'Aprimorar o ambiente de infraestrutura tecnológica onde os sistemas administrativos do TJGO são executados', 'DITI', 'Dez/2026',
   'Melhorar o desempenho e adequar a segurança e quantidade de recursos computacionais demandados pelos sistemas administrativos do TJGO, frente ao crescente número de acessos.',
   'Código de InfraOps implantado em camadas hierárquicas.', 'Não', 'INFRA', 'KR1', 'ON05, ON08', 'MACRO12 e MACRO18'),
  ('AG46', 'Atualizar os sistemas operacionais em EOL (End of Life)', 'DITI', 'Dez/2026',
   'Garantir que as atualizações dos fabricantes sejam realizadas para todos os sistemas operacionais em execução no ambiente de infraestrutura do TJGO',
   'Ter disponível no ambiente de infraestrutura do TJGO o percentual de no máximo 10% de sistemas operacionais em situação de EOL (End of Life)', 'Não', 'INFRA', 'KR1', 'ON07', 'MACRO12 e MACRO18'),
  ('AG47', 'Cumprir o Plano de Ação de Segurança da Informação - Bienio 2025/2026', 'DITI', 'Dez/2026',
   'Atender os requisitos impostos Resolução nº 396/2021 do CNJ, bem como a Portaria nº 162/2021.',
   'Elevação da maturidade de segurança da informação no TJGO', 'Não', 'INFRA', 'KR1', 'ON07', 'MACRO12 e MACRO18'),
  ('AG48', 'Implementar um Data Warehouse (DW) para integração dos dados dos Sistemas Administrativos do TJGO', 'SGJT', 'Concluída',
   'Os dados dos sistemas administrativos estão dispersos em diferentes bases, dificultando a consolidação, análise e geração de relatórios estratégicos. A ausência de um repositório centralizado compromete a eficiência na obtenção de informações gerenciais, impactando a tomada de decisão e a transparência na gestão.',
   'Centralização e integração dos dados administrativos por meio de um Data Warehouse (DW), o que proporcionará maior agilidade na extração de informações e qualidade dos relatórios, que, por consequência, resultará em uma gestão mais eficiente que trabalhará com dados estruturados e acessíveis para embasar decisões estratégicas.', 'Não', 'SIS', 'KR1', 'ON05, ON07', 'MACRO12 e MACRO18'),
  ('AG49', 'Implantar a etapa final do Portal de Governança de TIC', 'GEJUT', 'Dez/2026',
   'Entregar a etapa final do Portal de Governança de TIC contendo as informações completas de todas as abas e todos os planos previstos devidamente publicados.',
   'Portal da Governança de TIC com todos os "Indicadores" disponíveis e Planos publicados.', 'AG054 2023/25', 'PRIN', 'KR1', 'ON01, ON02, ON05', 'MACRO12 e MACRO18'),
  ('AG50', 'Desenvolver aplicativo móvel do sistema PROAD (Sistema de Processo Administrativo)', 'DSTI', 'Concluída',
   'Estruturar, priorizar e otimizar a entrega de soluções tecnológicas, garantindo mais eficiência e inovação no Judiciário.',
   'Aplicativo móvel do PROAD', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON05, ON08', 'MACRO12 e MACRO18'),
  ('AG51', 'Aprimorar o sistema TJDOCS a fim de possibilitar melhor controle e localização dos atos normativos', 'DSTI', 'Dez/2026',
   'Estruturar, priorizar e otimizar a entrega de soluções tecnológicas, garantindo mais eficiência e inovação no Judiciário.',
   'Novo sistema TJDOCs', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON05, ON08', 'MACRO12 e MACRO18'),
  ('AG52', 'Unificar o sistema de Jurisprudência', 'DSTI', 'Concluída',
   'Substituir os sistemas legados do TJGO com o objetivo de eliminar custos com licenças de tecnologias proprietárias, garantir segurança por meio de tecnologia moderna e promover eficiência e homogeneidade tecnológica.',
   'Sistema único de Jurisprudência e com os legados descontinuados.', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON05, ON08', 'MACRO12 e MACRO18'),
  ('AG53', 'Concluir o desenvolvimento do Sistema Integrado Financeiro (SIF)', 'DSTI', 'Dez/2026',
   'Substituir os sistemas legados do TJGO com o objetivo de eliminar custos com licenças de tecnologias proprietárias, garantir segurança por meio de tecnologia moderna e promover eficiência e homogeneidade tecnológica.',
   'Sistema Integrado Financeiro (SIF) com os seguintes módulos disponíveis: Arrecadação, Controle, RPV e Precatório.', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON05, ON08', 'MACRO12 e MACRO18'),
  ('AG54', 'Desenvolver novo sistema de controle de registros dos processos judiciais físicos arquivados', 'DSTI', 'Dez/2026',
   'Substituir os sistemas legados do TJGO (SPG, SSG e SED) com o objetivo de eliminar custos com licenças de tecnologias proprietárias, garantir segurança por meio de tecnologia moderna e promover eficiência e homogeneidade tecnológica.',
   'Novo sistema para consulta das informações de processos judiciais arquivados,', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON05, ON08', 'MACRO12 e MACRO18'),
  ('AG55', 'Desenvolver aplicativo móvel do sistema de processo judicial do TJGO (Projudi)', 'DSTI', 'Dez/2026',
   'Estruturar, priorizar e otimizar a entrega de soluções tecnológicas, garantindo mais eficiência e inovação no Judiciário.',
   'Aplicativo móvel do sistema de processo judicial do TJGO', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON05, ON08', 'MACRO12 e MACRO18'),
  ('AG56', 'Evoluir sistema processual judicial (PROJUDI)', 'DSTI', 'Dez/2026',
   'Estruturar, priorizar e otimizar a entrega de soluções tecnológicas, garantindo mais eficiência e inovação no Judiciário.',
   'Nova versão com melhor usabilidade do sistema de processo judicial digital', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON05, ON08', 'MACRO12 e MACRO18'),
  ('AG57', 'Evoluir a integração dos sistemas processuais à IA.', 'DSTI', 'Dez/2026',
   'Evoluir os sistemas processuais com Inteligência Artificial (IA) buscando eficiência, automação e transparência da gestão judicial e administrativa.',
   'IA integrada nos sistemas processuais desenvolvidos pelo TJGO.', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON05, ON08', 'MACRO12 e MACRO18'),
  ('AG58', 'Desenvolver ecossistema de Business Intelligence (BI) para o sistema de processo judicial do TJGO.', 'DSTI', 'Dez/2026',
   'Aprimorar a estratégia de análise de dados, permitindo análise em tempo real e melhoria nos processos de tomada de decisão.',
   'Paineis de BI que permitirão análise de dados em tempo real, otimizando a gestão e melhorando as tomadas de decisões estratégicas.', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON05, ON08', 'MACRO12 e MACRO18'),
  ('AG59', 'Criar procedimentos operacionais padronizados para gerenciamento dos sistemas desenvolvidos pelo TJGO.', 'DSTI', 'Concluída',
   'Otimizar e dar transparência aos procedimentos de solicitação de manutenções corretivas dos sistemas administrativos e judiciais do TJGO',
   'Processos de trabalho fomalizados, padronizados e otimizados para atender as solicitações de manutenção e gerencimento dos sistemas.', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON05, ON08', 'MACRO12 e MACRO18'),
  ('AG60', 'Encerrar o Plano de Diretor de Tecnologia da Informação e Comunicação – PDTIC', 'GEJUT', 'Jan/2027',
   'Preparar o documento de encerramento do Plano Diretor de Tecnologia da Informação e Comunicações do biênio 2025/27.',
   'Documento de encerramento do Plano Diretor de TIC validado e publicado no Portal de Governança de TIC.', 'Não', 'PRIN', 'KR1', 'ON05', 'MACRO12 e MACRO18'),
  ('AG61', 'Revisar o Plano Anual de Capacitação de Tecnologia da Informação e Comunicação – PACTIC', 'GEJUT', 'Concluída',
   'Preparar o documento de revisão obrigatória programada para o segundo semestre de 2025 do Plano Anual de Capacitação de Tecnologia da Informação e Comunicações da Secretaria de Governança Judiciária Tecnológica para biênio 2025/27.',
   'Documento publicado no Portal de Governança de TIC do TJGO.', 'Não', 'PRIN', 'KR1, KR3', 'ON05', 'MACRO12 e MACRO18'),
  ('AG62', 'Implantar processo de documentação, padronização e controle das solicitações de ativos de TI', 'CSTI', 'Concluída',
   'Implantar processo formal de documentação, padronização e controle das solicitações de ativos de TI, com o objetivo de organizar a demanda, assegurar rastreabilidade, uniformidade de critérios e alinhamento às diretrizes de governança e gestão de ativos do TJGO.',
   'Maior transparência, eficiência e controle na gestão das solicitações de ativos de TI, reduzindo inconsistências, otimizando o uso dos recursos disponíveis e apoiando a tomada de decisão baseada em informações confiáveis.', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON04, ON05, ON06, ON07 e ON08', 'MACRO9 e MACRO12'),
  ('AG63', 'Desenvolver painéis de Business Intelligence (BI) para monitoramento dos indicadores de desempenho dos serviços prestados pela CSTI', 'CSTI', 'Concluído',
   'Desenvolver painéis de Business Intelligence (BI) para consolidar, analisar e acompanhar de forma sistemática os indicadores de desempenho dos serviços prestados pela CSTI, garantindo maior visibilidade, padronização e confiabilidade das informações gerenciais.',
   'Possibilidade de monitoramento contínuo e em tempo real do desempenho dos serviços da CSTI, apoiando a tomada de decisão baseada em dados, o aprimoramento dos níveis de serviço, a identificação de gargalos operacionais e o fortalecimento da governança e da gestão por resultados.', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON04, ON05, ON06, ON07 e ON08', 'MACRO9 e MACRO12'),
  ('AG64', 'Encerrar o Plano Anual de Capacitação de Tecnologia da Informação e Comunicação – PACTIC', 'GEJUT', 'Concluída',
   'Preparar o documento de encerramento do Plano Anual de Capacitação de Tecnologia da Informação e Comunicações de 2025.',
   'Documento de encerramento do Plano Anual de Capacitação de TIC aprovado e publicado no Portal de Governança de TIC', 'Não', 'PRIN', 'KR1, KR3', 'ON05', 'MACRO12 e MACRO18'),
  ('AG65', 'Instituir o Plano Anual de Capacitação de Tecnologia da Informação e Comunicação – PACTIC', 'GEJUT', 'Concluída',
   'Preparar Plano de Capacitação de TIC para promover o desenvolvimento contínuo das competências dos profissionais da área. O plano alinha as ações de capacitação às necessidades estratégicas da instituição e às demandas tecnológicas. O plano terá vigência anual para 2026 e será acompanhado conforme as necessidades institucionais.',
   'Plano Anual de Capacitação de TIC aprovado e publicado no Portal de Governança de TIC', 'Não', 'PRIN', 'KR1, KR3', 'ON05', 'MACRO12 e MACRO18'),
  ('AG66', 'Implementar o MTD 1.2', 'SGJT', 'Mar/2026',
   'A Portaria nº 471 de 18/12/2025 do CNJ, que trata do edital do Prêmio CNJ de Qualidade 2026, contém vários itens que exige o envio dos dados comprobatórios na versão 1.2 do MTD para pontuação no prêmio.',
   'Dados adequados ao MTD 1.2 para pontuação no prêmio CNJ.', 'Não', 'SIS', 'KR1', 'ON05', 'MACRO1, MACRO09'),
  ('AG67', 'Revisar normativo de competências para recursos humanos de TIC', 'GEJUT', 'Mai/26',
   'Atualizar os critérios objetivos das competências gerenciais e técnicas para a escolha de líderes ocupantes das funções de Direção e Coordenação das unidades que compõem a área de TIC do Poder Judiciário Goiano.',
   'Documento publicado no Portal de Governança de TIC do TJGO.', 'Não', 'PRIN', 'KR1, KR3', 'ON03, ON05', 'MACRO12 e MACRO18'),
  ('AG68', 'Revisar normativo de metas e diretrizes para recursos humanos de TIC', 'GEJUT', 'Jul/26',
   'Atualizar metas específicas e diretrizes de desempenho para os recursos humanos que compõem a área de TIC, aperfeiçoando quando necessário os critérios de produtividades exigidos aos servidores lotados na SGJT.',
   'Documento publicado no Portal de Governança de TIC do TJGO.', 'Não', 'PRIN', 'KR1, KR3', 'ON05', 'MACRO12 e MACRO18'),
  ('AG69', 'Revisar o processo de Planejamento de Aquisições e de Contratações de Soluções de TIC', 'GEJUT', 'Jul/2026',
   'Revisar o processo de Planejamento de Aquisições e de Contratações de Soluções de TIC, registrado no Proad 202507000655637, em atenção à Resolução nº 468/2022 do CNJ, bem como à Lei de Licitações e Contratos Administrativos nº 14.133/2021',
   'Processo de Planejamento de Aquisições e de Contratações de Soluções de TIC revisado, aprimorado, padronizado e aprovado', 'Não', 'PRIN', 'KR1, KR2, KR3', 'ON05, ON06', 'MACRO9 e MACRO12'),
  ('AG70', 'Revisar o processo de Gerenciamento de Contratos de TIC', 'GEJUT', 'Jul/2026',
   'Revisar o processo de Gerenciamento de Contratos de TIC, registrado no Proad 202507000655232, em atenção à Resolução nº 468/2022 do CNJ, bem como à Lei de Licitações e Contratos Administrativos nº 14.133/2021.',
   'Processo de Gerenciamento de Contratos de TIC revisado, aprimorado, padronizado e aprovado.', 'Não', 'PRIN', 'KR1, KR2, KR3', 'ON05, ON06', 'MACRO9 e MACRO12'),
  ('AG71', 'Revisar o processo de Planejamento Orçamentário de TIC', 'GEJUT', 'Jul/2026',
   'Revisar o Processo de Planejamento Orçamentário de TIC, registrado no Proad 202507000655636, em atenção à Resolução nº 468/2022 do CNJ, bem como à Lei de Licitações e Contratos Administrativos nº 14.133/2021, da Presidência da República',
   'Processo de Planejamento Orçamentário de TIC revisado, padronizado e aprovado.', 'Não', 'PRIN', 'KR1, KR2, KR3', 'ON05, ON06', 'MACRO9 e MACRO12'),
  ('AG72', 'Revisar o Plano Anual de Capacitação de Tecnologia da Informação e Comunicação – PACTIC', 'GEJUT', 'Ago/26',
   'Preparar o documento de revisão obrigatória programada para o segundo semestre de 2026 do Plano Anual de Capacitação de Tecnologia da Informação e Comunicações da Secretaria de Governança Judiciária Tecnológica para biênio 2025/27.',
   'Documento publicado no Portal de Governança de TIC do TJGO.', 'Não', 'PRIN', 'KR1, KR3', 'ON05', 'MACRO12 e MACRO18'),
  ('AG73', 'Instituir o Projeto Concilia', 'SGJT', 'Ago/2026',
   'Sistema solicitado para auxiliar os conciliadores na elaboração de possíveis estratégias de conciliação.',
   'Aumento na taxa de conciliação, a partir do apoio de IA para auxiliar os conciliadores, vinculados ao NUPEMEC, na formulação e utilização de técnicas de acordos entre partes litigantes.', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON05', 'MACRO1, MACRO09'),
  ('AG74', 'Revisar o Processo de Gerenciamento de Projetos de Tecnologia da Informação e Comunicação', 'GEJUT', 'Set/26',
   'Estabelecer a revisão do processo de Gerenciamento de Projetos de TIC com o objetivo de aprimorar a padronização quanto a estrutura organizacional, a governança e a eficiência na condução dos projetos institucionais. A atualização busca adequar o processo às melhores práticas de gestão, fortalecer o acompanhamento das iniciativas e garantir maior alinhamento com os objetivos estratégicos.',
   'Processo de Negócio aprovado e publicado no Portal de Governança de TIC', 'Não', 'PRIN', 'KR1, KR3', 'ON05', 'MACRO12 e MACRO18'),
  ('AG75', 'Automatizar a Berna para Custas Iniciais', 'SGJT', 'Out/2026',
   'Ausência de mecanismo sistêmico de alerta para identificar parcelas de custas vencidas em processos com parcelamento deferido, o que dificulta o controle manual pelas unidades diante do elevado volume de atos processuais e favorece a tramitação de feitos com pendências financeiras não regularizadas.',
   'Disponibilização de alerta automatizado por meio da Berna, promovendo maior regularidade processual, redução de evasão indireta de custas, apoio às unidades e magistrados na fiscalização dos recolhimentos e fortalecimento da governança dos fluxos processuais.', 'Não', 'SIS', 'KR1', 'ON01, ON02, ON05, ON07', 'MACRO1, MACRO09'),
  ('AG76', 'Revisar o Processo de Gerenciamento de Capacitação em Tecnologia da Informação e Comunicação', 'GEJUT', 'Nov/26',
   'Estabelecer a revisão do processo de Gerenciamento de Capacitação de TIC, com o objetivo de aprimorar a identificação das necessidades de desenvolvimento, o planejamento das ações formativas e o acompanhamento dos resultados. O processo compreende as etapas de levantamento das demandas de capacitação, priorização das necessidades, planejamento e execução das ações de treinamento, bem como o monitoramento e avaliação dos resultados obtidos.',
   'Processo de Negócio aprovado e publicado no Portal de Governança de TIC', 'Não', 'PRIN', 'KR1, KR3', 'ON05', 'MACRO12 e MACRO18'),
  ('AG77', 'Revisar o Processo de Planejamento Tático-Operacional do Plano Diretor de Tecnologia da Informação e Comunicação', 'GEJUT', 'Nov/26',
   'Estabelecer a revisão do processo de Gerenciamento do Plano Diretor de TIC - PDTIC, com o objetivo de aprimorar o planejamento, o acompanhamento e a avaliação das ações estratégicas de TIC. O processo compreende as etapas de elaboração do plano, priorização das iniciativas, monitoramento da execução das ações e avaliação periódica dos resultados.',
   'Processo de Negócio aprovado e publicado no Portal de Governança de TIC', 'Não', 'PRIN', 'KR1, KR3', 'ON05', 'MACRO12, MACRO18'),
  ('AG78', 'Automatizar os Sistemas de Cobrança de Custas Judiciais', 'SGJT', 'Dez/2026',
   'Controle da cobrança de custas judiciais considerando que o controle atualmente é realizado de forma manual por meio de planilhas, o que demanda elevado esforço operacional, aumenta o risco de erros e compromete a efetividade da recuperação dos valores devidos.',
   'Automatização e padronização da cobrança de custas judiciais, com envio tempestivo para protesto em casos de inadimplência, redução do esforço operacional e de erros manuais, maior controle e rastreabilidade dos créditos, além de aumento da eficiência e da efetividade na recuperação dos valores devidos.', 'Não', 'SIS', 'KR1', 'ON05, ON07', 'MACRO9, MACRO12'),
  ('AG79', 'Desenvolver Sistema de Transferência de Depósitos Judiciais', 'SGJT', 'Dez/2026',
   'Necessidade de desenvolvimento de sistema específico para o controle dos valores transferidos ao Tribunal a título de depósitos judiciais, contemplando o registro e acompanhamento das movimentações, o cálculo automático de reajustes com base na taxa da poupança e nas taxas de aplicações financeiras do Tribunal, bem como o controle das eventuais devoluções. A ausência de ferramenta adequada compromete a precisão dos cálculos, a rastreabilidade das informações e a eficiência na gestão desses recursos',
   'Maior precisão e confiabilidade no controle dos depósitos judiciais transferidos ao Tribunal, com cálculo automático e padronizado dos reajustes, registro adequado das devoluções e rastreabilidade das movimentações, proporcionando mais eficiência, transparência e segurança na gestão desses recursos.', 'Não', 'SIS', 'KR1', 'ON05, ON07', 'MACRO9, MACRO12'),
  ('AG80', 'Encerrar o Plano Anual de Capacitação de Tecnologia da Informação e Comunicação – PACTIC', 'GEJUT', 'Jan/27',
   'Preparar o documento de encerramento do Plano Anual de Capacitação de Tecnologia da Informação e Comunicações de 2026.',
   'Documento de encerramento do Plano Anual de Capacitação de TIC aprovado e publicado no Portal de Governança de TIC', 'Não', 'PRIN', 'KR1, KR3', 'ON05', 'MACRO12 e MACRO18'),
  ('AG81', 'Implantar o Ponto Único de Contato (SPOC) de Tecnologia da Informação', 'CSTI', 'Jan/2027',
   'Centralizar e padronizar o recebimento, o registro, a triagem e o acompanhamento das demandas de TI no âmbito institucional.',
   'Consolidação de um canal oficial e estruturado de comunicação entre os usuários e a área de TI, assegurando maior controle, transparência e previsibilidade no atendimento das demandas.', 'Não', 'SUP', 'KR1', 'ON01, ON02, ON04, ON05, ON07 e ON08', 'MACRO9 e MACRO12'),
  ('AG82', 'Desenvolver Sistema de Gestão de Contratações', 'SGJT', 'Jan/2027',
   'Muito esforço no controle de contratações, tendo em vista que o acompanhamento atualmente é realizado por meio de planilhas e sistemas distintos e não integrados, o que exige elevado esforço manual para consolidação das informações e dificulta o controle adequado das etapas e execuções das demandas prevista no PCA.',
   'Centralização e integração das informações relativas às contratações, com automatização do acompanhamento das etapas e das demandas previstas no PCA, redução do esforço manual de consolidação de dados, maior controle e rastreabilidade dos processos, além de incremento na eficiência, confiabilidade das informações e capacidade de planejamento e gestão.', 'Não', 'SIS', 'KR1', 'ON05, ON06', 'MACRO9, MACRO12')
) AS v(id_pdtic, nome, diretoria, conclusao, necessidade, resultado, reagendada, classe, indicador, objetivos, macrodesafios)
WHERE NOT EXISTS (
    SELECT 1 FROM pdtic_acoes p
     WHERE p.id_pdtic = v.id_pdtic
       AND p.is_deleted = FALSE
);

-- Conferência (deve retornar 82 se rodou do zero):
-- SELECT count(*) FROM pdtic_acoes WHERE id_pdtic LIKE 'AG%' AND is_deleted = FALSE;

COMMIT;
